### ISSUE TITLE
login disappears when screen gets too small

### ISSUE THREAD

**Issue by tk7r** [coreui/coreui-free-bootstrap-admin-template#102]
The login menu in the top right corner is hidden when the screen gets too small (smartphone format). In small screen mode reaching the login is not possible. Is there a standard or a suggestion for an alternative location of the login (logout, profile) menu for small screens?

**Comment by mrholek** [comment]
Which version are you using? AngularJS, Angular2, React or jQuery/Static ?

**Comment by tk7r** [comment]
I am using Angular2 primarily.
Login disappers : AngularJS, Angular2, jQuery/Static.
Login works on small screen : React.
Tested with the examples on coreui.io <http://coreui.io/> with Safari/macOS Sierra, Chrome/macOS Sierra and iPhone 7/iOS 10.2.1.

**Comment by ezzkht** [comment]
I see that the Sign Up section disappears, but the Login section stays there.
I tried that on IE 11, FF and Chrome and Login never disappear.

**Comment by mrholek** [comment]
Fixed
