### ISSUE TITLE
How scss files are compiled in react templates

### ISSUE THREAD

**Issue by hhsadiq** [coreui/coreui-free-bootstrap-admin-template#103]
I am curious how scss files are compiled in react templates, because there is no mention of `node-sass` neither we are using webpack based sass compilation nor any other sass compiler. So how is it compiled? Sorry if I missed something very trivial.

**Comment by hhsadiq** [comment]
I guess you are using separate sass watchers to compile it and replace public/css/style.css. There is similar discussion on create react app github repo where Facebook guys were suggesting somewhat similar approach. I am still looking for more benefits to it.

**Comment by mrholek** [comment]
At this moment I use gulp to compile SCSS Files, if you have better idea I'm open to suggestions.

Can you share with me link to discussion with Facebook guys?

**Comment by hhsadiq** [comment]
Have a look at this [comment](https://github.com/facebookincubator/create-react-app/issues/78#issuecomment-245727905) by @gaearon; a contributor to create-react-app. Although reading full thread is very helpful...And here is screenshot where he is talking somewhat similar.

![image](https://cloud.githubusercontent.com/assets/8002757/22618325/5ed7c4d6-eafb-11e6-9e30-65fe2ba0d02c.png)

**Comment by hhsadiq** [comment]
So based on his suggestions, it looks better option to go with what you are doing. But speaking of ease for multiple developers working on single project, the solution where we eject the app and use webpack based sass loaders looks easier.

I am stilling balancing the pros and cons of different options, so still a confused guy :-)

**Comment by hhsadiq** [comment]
FYI, so finally decided to use gulp watchers in background as suggested by @gaearon (Dan Abromov)..

**Comment by mrholek** [comment]
In latest version I added some gulp tasks to watch and compile SCSS to CSS

**Comment by mariusa** [comment]
Hello @mrholek 

>In latest version I added some gulp tasks to watch and compile SCSS to CSS
Would it be possible to please add that to vue project too?

Editing style.scss or _custom.scss has no effect, not even on build
static/css/style.css never changes.

Thanks!

**Comment by mariusa** [comment]
Actually, this issue should be closed. See issue #230
