### ISSUE TITLE
reactjs

### ISSUE THREAD

**Issue by pepepaco** [coreui/coreui-free-bootstrap-admin-template#115]
reactjs demo is not working on ie11 nor safari.
I think is missing some polyfills.
thanks.

**Comment by mrholek** [comment]
I just checked it and everything is ok.

IE 11
![zrzut ekranu 2017-02-23 o 14 58 16](https://cloud.githubusercontent.com/assets/3524167/23261870/b51e391a-f9d8-11e6-97e5-a90955e933e2.png)

Safari
<img width="1440" alt="zrzut ekranu 2017-02-23 o 14 58 16 2" src="https://cloud.githubusercontent.com/assets/3524167/23261873/bb4c144c-f9d8-11e6-97f9-74b7162c1c78.png">

**Comment by pepepaco** [comment]
Thank you , I'll try from another computer later today, 
in the mean time if possible could you please try the published site please?

http://coreui.io/demo/React_Demo/#/

thanks!

**Comment by joelsand** [comment]
Public demo doesn't work for me on IE11, either.  Haven't tried it locally.

![image](https://cloud.githubusercontent.com/assets/113564/23907522/6ce4df7a-089f-11e7-9227-a5e29bf18cc8.png)
