### ISSUE TITLE
Any plan for Angular 2 Server side rendering

### ISSUE THREAD

**Issue by imVinayPandya** [coreui/coreui-free-bootstrap-admin-template#116]
your UI template is good, I have developed one project using core UI. but as soon I complete my project I am willing to make production ready app and for that, we need to take care of Google boat, SEO kind of things. especially for publishing your site with google console I need to do server side rendering.

so is there any solution for doing server-side rendering with core UI, angular-CLI??, Univer-CLI is not mature yet.

**Comment by mrholek** [comment]
We have a dedicated project for Angular, so you asked in the wrong place.
