### ISSUE TITLE
Tooltips in AngularJS

### ISSUE THREAD

**Issue by hrvylein** [coreui/coreui-free-bootstrap-admin-template#133]
Am I missing sth or isn't it possible to use Tooltips along with AngularJS? They show fine but it is not possible to add content to them, because instead of (for example) "red" the tooltip shows {{day.color}} (this is how I access the value red).

Any workaround for this? ng-attr-title is not working either.

**Comment by hrvylein** [comment]
using data-original-title instead of title solves the problem.

**Comment by hrvylein** [comment]
Well I found it out by myself. For example `data-html="true" data-original-title="{{day.tooltip}}"  data-toggle="tooltip" data-placement="bottom"` will display html served by angularjs.

**Comment by mrholek** [comment]
We have a dedicated project for Angular, so you asked in the wrong place.

**Comment by hrvylein** [comment]
Sometimes time is just flying by.
