### ISSUE TITLE
Aurelia JS support

### ISSUE THREAD

**Issue by enrico-padovani** [coreui/coreui-free-bootstrap-admin-template#138]
Hi,

Is there a planned support for Aurelia? I'll be also interested in buying a premium template version.

Thanks for the nice work done.

**Comment by mrholek** [comment]
At this moment we don't have enought resource to support Aurelia JS

**Comment by dannyweldon** [comment]
Would it be possible to include the Aurelia icon on your website though, as your Aurelia template is working okay?  You don't need to provide a separate repo for the Aurelia version as we can just use the subfolder in the main repo and I may be able to provide a tutorial for the Aurelia community on how to use it, which will increase interest in your template.
