### ISSUE TITLE
Angular4_CLI_Full_Project Select box some words height problem ?

### ISSUE THREAD

**Issue by caglarturkurka** [coreui/coreui-free-bootstrap-admin-template#146]
Thanks for your Angular 4 template.I noticed that select box has got height problem when we use some words like 'g' and 'y' in your last version of Angular 4 CLI Full Project.Could you check and fix it ?. Thanks again for your attention.

<img width="101" alt="selectboxproblem" src="https://cloud.githubusercontent.com/assets/6197613/25042303/9d6dfbe8-211f-11e7-8937-4c2fe301bd7e.png">

**Comment by mrholek** [comment]
We have a dedicated project for Angular, so you asked in the wrong place.
