### ISSUE TITLE
ngStyle not work in child routing component

### ISSUE THREAD

**Issue by sichengde** [coreui/coreui-free-bootstrap-admin-template#153]
when i use <div [ngStyle]="{color: 'red'}"></div> in full-layout.component , its ok 
when i use it in child routing component dashboard, it not work,
got "Can't bind to 'ngStyle' since it isn't a known property of 'div'"

**Comment by corywmoore** [comment]
I ran into the same issue with ngIf. I resolved by importing CommonModule to all the child modules.

**Comment by markzolotoy** [comment]
But when I import CommonModule  into the app module it says duplicate.

**Comment by markzolotoy** [comment]
I imported it into my component ts file. Still the error is the same.

**Comment by markzolotoy** [comment]
Plus, I dont see that import in default-layout.component.ts which as it says works fine.

**Comment by mrholek** [comment]
@markzolotoy this repository is dedicated to bootstrap version, we have a separate repository dedicated angular version - https://github.com/coreui/coreui-free-angular-admin-template please add your question here.

**Comment by markzolotoy** [comment]
Already figured out. I had to import CommonModule into a module that is a
parent to a component that uses ngStyle.
