### ISSUE TITLE
How to implement Angular2_Dev on ASP.NET Core?

### ISSUE THREAD

**Issue by FacundoGFlores** [coreui/coreui-free-bootstrap-admin-template#16]
Hello everyone.

I am using the yeoman generator: [aspnetcore-angular2](https://www.npmjs.com/package/generator-aspnetcore-angular2) and I want to include this project template. Can someone help me to integrate CoreUI into ASP.NET project?

**Comment by FacundoGFlores** [comment]
For those who are interested I have implemented the integration, the code is available in my [repo][1].


  [1]: https://github.com/FacundoGFlores/Angula2_ASPCORE

**Comment by gary-holland** [comment]
@FacundoGFlores repo didn't seem to be complete, so I implemented a .net core version of the CoreUI myself.  [repo here](https://github.com/gary-holland/CoreUI-Starter)

**Comment by FacundoGFlores** [comment]
@gary-holland are you using angular-cli?

**Comment by gary-holland** [comment]
@FacundoGFlores the repo I linked to is not using angular-cli, it's based on .net template from this (blog](http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/).  

I prefer the angular-cli, and have recently switched my work over to a setup similar to (this)[https://devblog.dymel.pl/2016/10/25/angular2-cli-with-aspnet-core-application-tutorial/], which is working well for me.
