### ISSUE TITLE
Angular4_CLI_Full_Project has an issue with defining component styles

### ISSUE THREAD

**Issue by dbaranau** [coreui/coreui-free-bootstrap-admin-template#170]
If you define styles for a component by using styles: [] or styleUrls: [] - neither of them work.

The only way to define styles is by adding them to app/scss/_custom.scss.

Please fix, thanks.

**Comment by puppeteer701** [comment]
IS there any progress on this issue?

**Comment by mrholek** [comment]
We have a dedicated project for Angular, so you asked in the wrong place.
