### ISSUE TITLE
Considering buying this, but can't figure out how to use in Meteor

### ISSUE THREAD

**Issue by nadeemja** [coreui/coreui-free-bootstrap-admin-template#172]
Hi,

Has anyone figured out how to use this in Meteor with React? 

@mrholek, will this work with Meteor?

**Comment by BersnardC** [comment]
Hi @nadeemja. Meteor work with Blaze, but is easy  integrates with react, angularjs, vuejs and other technologies. I recommend this tutorial on the meteor page, that explanied like implemmente react app meteor app: https://www.meteor.com/tutorials/react/creating-an-app . Is very easy and elegant. Be happy, regards! :+1:

**Comment by BersnardC** [comment]
I hope help you! :-)

**Comment by nadeemja** [comment]
Thanks for the answer @BersnardC. However, I already know how to use react with meteor. We're using MantraJS in our app. I just can't figure out how to actually use this theme. Do you have an example where you're using this theme with meteor and react? How do you actually use the components?
