### ISSUE TITLE
 The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by shenhf** [coreui/coreui-free-bootstrap-admin-template#174]
$ yarn add coreui
yarn add v0.24.5
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error jss@5.5.6: The engine "node" is incompatible with this module. Expected version ">=5.0.0 <7.0.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

$ node --version
v7.10.0

**Comment by deuceBag33** [comment]
+1

**Comment by Phirames** [comment]
+1

**Comment by aliasad106** [comment]
+1
