### ISSUE TITLE
How I can run?

### ISSUE THREAD

**Issue by Fujiatma** [coreui/coreui-free-bootstrap-admin-template#187]
how to run it?

**Comment by roselykm** [comment]
Learn angular first then come back here, otherwise you will not be able to use the template.

**Comment by deksoke** [comment]
read document at https://cli.angular.io/

**Comment by Bloggerschmidt** [comment]
- download it
- unpack it
- open dir in terminal (e.g. Angular_Full_Project_GULP)
- `bowser install`
- `gulp`
