### ISSUE TITLE
Improvement: Link the css using a git submodule

### ISSUE THREAD

**Issue by sterlp** [coreui/coreui-free-bootstrap-admin-template#189]
Hello guys,

it seems to me that core-ui is included in each example project. What about if it is just included using a git submodule containing just the scss files?

As I build the JEE Angular example (wro4j pull request is still pending) and if would build the same using angular 4 I would need to copy core-ui again right? Or did I just missed something?
_(Everything in the scss folder)_

Cheers,

Paul

**Comment by griffiti** [comment]
I like this idea. Starting with the example templates is great. But being able to reference the CoreUI files as a submodule allows for other ways to integrate. Alternatively, offering CoreUI as a Bower and NPM package would also be helpful for front-end development and tool integration.

**Comment by sterlp** [comment]
True. A webjar in the maven repository would be also really cool, for Java projects.
