### ISSUE TITLE
npm run start in React_Full_Project results in ERR! 

### ISSUE THREAD

**Issue by tmayer88** [coreui/coreui-free-bootstrap-admin-template#193]
![screen shot 2017-06-23 at 3 27 34 pm](https://user-images.githubusercontent.com/29665438/27499128-545d8110-5830-11e7-924f-0830e0573448.png)

**Comment by mcgradycchen** [comment]
Hi tmayer88,

I was facing the same issue. 
After I upgrade my node version from v4.4.3 to v6.11.0 . The error is gone.
