### ISSUE TITLE
Improvement: Offer Bower and NPM Packages

### ISSUE THREAD

**Issue by griffiti** [coreui/coreui-free-bootstrap-admin-template#195]
I would like to see CoreUI offered as Bower and NPM packages. This would expand options for front-end and back-end integration.

**Comment by Qrzysio** [comment]
I'm surprised there is no bower option to install CoreUI.

**Comment by mrholek** [comment]
We decided to move different versions to separate repositores, so they will support bower and npm soon.

* [Angular Version (Angular 2+)](https://github.com/mrholek/CoreUI-Angular).
* [AngularJS Version](https://github.com/mrholek/CoreUI-AngularJS).
* [HTML5 AJAX Version](https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template).
* [HTML5 Static Version](https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template).
* [React.js Version](https://github.com/mrholek/CoreUI-React).
* [Vue.js Version](https://github.com/mrholek/CoreUI-Vue).

**Comment by Qrzysio** [comment]
Bower is deprecated. One should use npm. Bower recommends also Yarn.

Separating versions is very good idea!
