### ISSUE TITLE
None of the responsive utilities work

### ISSUE THREAD

**Issue by snarlynarwhal** [coreui/coreui-free-bootstrap-admin-template#201]
None of the responsive utilities work.. might be a Bootstrap 4 issue and not a Core UI one though.

When I visited the [Test Cases](http://coreui.io/docs/layout/responsive-utilities) page, every case stayed green no matter how big or small I made my browser window.

**Comment by danielcoates** [comment]
I'm getting similar behaviour, although it only seem to be affecting `hidden-*-up` and `hidden-*-down` and not  `hidden-*-only`. some screenshots bellow.

![coreui io-docs-layout-responsive-utilities](https://user-images.githubusercontent.com/19962341/28123442-ddc61d58-6718-11e7-83e9-fbf39c8b2c46.png)

![coreui io-docs-layout-responsive-utilities ipad 1](https://user-images.githubusercontent.com/19962341/28123443-ddcb3716-6718-11e7-8d37-6c1004a95446.png)

![coreui io-docs-layout-responsive-utilities ipad 2](https://user-images.githubusercontent.com/19962341/28123445-ddccefa2-6718-11e7-8c4c-0cff651ecef4.png)

![coreui io-docs-layout-responsive-utilities iphone 6 plus](https://user-images.githubusercontent.com/19962341/28123446-ddd68f30-6718-11e7-918e-f8424daf2dae.png)

**Comment by xidedix** [comment]
The bulk of  ```.hidden-``` classes have been removed from Bootstrap v4 alphas in favor of display utilities.

**Comment by amint** [comment]
Similar issues here too. User menu disappears in mobile view too.

**Comment by adam-hanna** [comment]
@xidedix how so? They have a documentation page for them, [here](https://v4-alpha.getbootstrap.com/layout/responsive-utilities/).

**Comment by adam-hanna** [comment]
FIXED!

It looks like bootstrap and reactstrap aren't properly installed in the react version of this kit. I had to follow the reactstrap installation instructions for adding bootstrap, [found here](https://github.com/reactstrap/reactstrap#adding-bootstrap).

```bash
$ npm install --save bootstrap@4.0.0-alpha.6
$ npm install --save reactstrap react-transition-group@^1.1.2 react@^15.3.0 react-dom@^15.3.0
```

```javascript
// index.js
import 'bootstrap/dist/css/bootstrap.css';
```

**Comment by snarlynarwhal** [comment]
No luck fixing it :/ Any other steps I may have missed?

**Comment by mrholek** [comment]
We use this version of bootstrap https://github.com/twbs/bootstrap, it's newer then alpha.6. In next version of bootstrap ( beta.1) responsive utilities will be removed.

Please download documentation to latest version of Bootstrap from github and check it https://github.com/twbs/bootstrap

**Comment by snarlynarwhal** [comment]
Okay thank you very much!
