### ISSUE TITLE
when running ng test - got a 'router-outlet' is not a known element - error - Angular 4

### ISSUE THREAD

**Issue by henry-hz** [coreui/coreui-free-bootstrap-admin-template#202]
Trying to run "ng test" on angular4 starter application. 

I am using : 
node v8.1.4 
npm 5.0.3 

```
Error: Template parse errors:
'router-outlet' is not a known element:
1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<router-outlet></router-outlet>"): ng:///DynamicTestModule/AppComponent.html@0:0
```

**Comment by mokipedia** [comment]
getting the same here

**Comment by mokipedia** [comment]
For everyone else having this issue:

in app.component.spec.ts
`import {RouterTestingModule} from '@angular/router/testing' ` 
+ add imports to TestBed
`beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent
      ],
      imports: [
        RouterTestingModule
      ]
    });`

**Comment by ManfredGit** [comment]
using mokipedia's solution, not work for me.

**Comment by mikegitrepo** [comment]
@mokipedia  is awesome. My error gone.

**Comment by housseinimaiga** [comment]
@mokipedia  solution works fine for me, thxs guy 👍

**Comment by Qocotzxin** [comment]
@mokipedia Thanks, that's THE solution! Just in case someone uses the Atom's Angular snippet, the spec file does not include the "import" array by default so you will have to add it to the configureTestingModule by yourself, and include only the RouterTestingModule

**Comment by mokipedia** [comment]
thats cool that it helps.
Just wanted to follow up for everyone else having this issues:
coreui meems to have moved angular5 development to a new repository: https://github.com/mrholek/CoreUI-Angular

**Comment by antonelladivirgilio** [comment]
@mokipedia It worked! Thanks!
