### ISSUE TITLE
scrollable column support?

### ISSUE THREAD

**Issue by ronnyek** [coreui/coreui-free-bootstrap-admin-template#205]
Greetings... I'm impressed with the template, and am primarily tinkering with an angular2 template. 

What I'd like to do is be able to have left sidebar, then say another column similar in size scrollable but filling vertical height, and then a third column filling the remaining horizontal space.

I tried setting flex none for a column that 100% height, and overflow-y: scroll. Then had the final column flex 1 auto. Seems like I can ALMOST get this to work, though wide content causes the 3rd column to extend past the constraints of the browser. 

I'm not super familiar with the css grid stuff you use, is it just bootstrap4? do you have recommendations about how one could set something like this up?

Desired layout is similar to outlook, where you have first nav pane on the left, then then inbox list of items, that is independently scrollable from other areas, then the details view of the conversation which is effectively 100% of the remaining horizontal and vertical space, and ultimately scrollable.

https://upload.wikimedia.org/wikipedia/en/c/cf/Outlook_for_Mac_2016_screenshot.png

I must be missing osmething.

**Comment by ronnyek** [comment]
I didnt realize that this existed: http://coreui.io/docs/getting-started/introduction

I went ahead and created a layout with a sidebar/header/content tab and then just played with flex classes as laid out in those docs... I am getting close (just not quite there YET)

**Comment by guilhermeaiolfi** [comment]
I'm trying the same thing, but it opens the door for a lot of problems when dealing with mobile devises. Have you been able to create something that would work for mobiles too?
