### ISSUE TITLE
Angular 4 - adding theme switch option for user

### ISSUE THREAD

**Issue by dorjeduck** [coreui/coreui-free-bootstrap-admin-template#226]
Hi,
I really love Coreui for its very well done coding style compared to many other angular templates out there. Thanks a lot. 
I would love to add the possibility to change the theme for the user, lets say a dark theme next to the default theme, and have no idea right now how to implement that. Any suggestion highly appreciated.

martin

**Comment by korn3l** [comment]
You can modify _bootstrap-variables.scss and _core-variables.scss if you want to change the default values.
To see all the variables that can be changed you can check out scss/bootstrap/_variables.scss and scss/code/_variables.scss respectively.
