### ISSUE TITLE
build: load some resources from CDNs, instead of bundling

### ISSUE THREAD

**Issue by mariusa** [coreui/coreui-free-bootstrap-admin-template#227]
Please provide an option to load some resources from CDNs, instead of bundling everything.
example: font-awesome, or some JS files in vendor.js

In the demo, vendor.js is 447kb. Using CDNs would ease the load on app server.
http://coreui.io/demo/Vue_Demo/#/dashboard

Thanks

**Comment by danielcoates** [comment]
+1 for this
