### ISSUE TITLE
Modals behavior

### ISSUE THREAD

**Issue by xirapo** [coreui/coreui-free-bootstrap-admin-template#253]
Hey ,
Im using the Static version of coreui , and i notice that if i create more than one modal , i have to use them in a specific order example:

create 
update
delete

the createModal was created first but in order to work ,i must open delete first follow by update only them create will work.

Anyone got any idea how to fix it.

sorry if i miss spell some words english is not my native language.

**Comment by iamjonmiller** [comment]
+1 Trying to figure this one out

**Comment by xidedix** [comment]
possibile duplicate #235

**Comment by kitloong** [comment]
Hi,

I able fixed this issue by comment out line 31 in scss/core/_temp.scss
.modal-open .modal {
  display: block;
}

**Comment by nerdv2** [comment]
@kitloong still doesn't work for me, is anybody else had tried and test it?

**Comment by nerdv2** [comment]
Removing the same code in the css/style.css on line 8593 working though.

**Comment by iamjonmiller** [comment]
going to try removing it from line 8593

**Comment by iamjonmiller** [comment]
Can confirm this worked for my project. Modals can now be opened and closed in any order and with any number.

**Comment by kitloong** [comment]
Hi @nerdv2 , if you are not compile with scss yes you need to edit in css/style.css

**Comment by nerdv2** [comment]
Is the problematic code part of the template or bootstrap 4?

**Comment by iamjonmiller** [comment]
It is part of CoreUI. Regular Bootstrap 4 Beta modals work with no changes.

**Comment by ShackaL86** [comment]
/*.modal-open .modal {
  display: block;
}*/

After commenting on the code, the modal window starts working fine, but after that you can close the window by clicking anywhere on the screen. It is not good. How can I fix this?

**Comment by kitloong** [comment]
@ghost Modal behavior is part of Bootstrap Modal feature. 
Check out `backdrop` from [here](http://getbootstrap.com/docs/4.0/components/modal/#options)
