### ISSUE TITLE
Sidebar toggler isn't working for me

### ISSUE THREAD

**Issue by rhowells** [coreui/coreui-free-bootstrap-admin-template#279]
```
<header class="app-header navbar" ng-controller="header">
	<a class="navbar-brand" href="/"></a>
	<button class="navbar-toggler sidebar-toggler d-md-down-none" type="button">☰</button>
	<ul class="nav navbar-nav ml-auto" style="padding-right:20px">
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
				<img src="img/user.png" class="img-avatar">
				<span class="d-md-down-none">{{username}}</span>
			</a>
			<div class="dropdown-menu dropdown-menu-right ">
				<div class="dropdown-header text-center">
					<strong>Settings</strong>
				</div>
				<a class="dropdown-item" href="#" ng-click="logout()"><i class="fa fa-lock"></i> Logout</a>
			</div>
		</li>
	</ul>
</header>
```

`<body ng-app="app" class="footer-fixed sidebar-fixed">`

If I switch to `<body ng-app="app" class="footer-fixed sidebar-hidden">` it successfully hides but still doesn't toggle.

Edit:

Using jQuery v3.2.1, Bootstrap v4.0.0-beta

Tried switching to Bootstrap v3.3.7 which didn't help.

**Comment by daveio** [comment]
@rhowells Are you using Rails? Specifically, Turbolinks? I have that issue and I have a fix if you're hitting the same failure mode.

**Comment by jsmestad** [comment]
@daveio I am hitting the issue. I do have turbolinks on, what was the fix?

**Comment by daveio** [comment]
@jsmestad It's been a while but from memory, the issue is with the progress bar javascript. Remove pace.js and things may work. If they don't, the other thing I did was to get Turbolinks to re-initialise everything with a load hook. I actually re-implemented all the CoreUI Javascript in Coffeescript, adding a function called init_ui() which set $.init_done to true. The following coffeescript showing the hook setup might make things clearer:

```coffeescript
$(document).on 'turbolinks:load', ->
  init_ui($)

$(document).ready ->
  init_ui($) unless $.init_done
```

**Comment by yonggu** [comment]
@daveio Could you please share your Coffeescript file? I am also encountering the same problem.

**Comment by ubugnu** [comment]
Can you please further explain which hack you have done to make coreui js works with turbolinks?

**Comment by luislezcair** [comment]
I recently stumble upon this issue. I made it work with this:

```javascript
document.addEventListener('turbolinks:load', () => {
   $('.sidebar').sidebar();
   $('.aside-menu')['aside-menu']();
});
```

**Comment by ubugnu** [comment]
@luislezcair thank you! really!

**Comment by ubugnu** [comment]
To whom it may concern, as for coreui v2.1.3 it is now:

```javascript
document.addEventListener('turbolinks:load', () => {
   $('.sidebar-nav').sidebar();
});
```
