### ISSUE TITLE
path for bootstrap components in scss/vendors/variables.scss 

### ISSUE THREAD

**Issue by maddinq** [coreui/coreui-free-bootstrap-admin-template#286]
"node/xyz" can't work
looks like "/node/xyz" isn't working too. 
any idea ? 
I would like to use the node_modules bootstrap instead of maintaining a copy in the scss folder

**Comment by xidedix** [comment]
We are going to use node_modules for bootstrap in next release if possible. Stay tuned.

**Comment by maddinq** [comment]
maybe you can use webpack. 
but please do some little adjustments on the gulp jobs too. 
e.g. build-dist.js - I renamed the gulp.paths.dist variable but you still have static paths (line 110 (replace:node_modules)) ..should use the variable too. 

Generally is there any preferred way to communicate with you ?
