### ISSUE TITLE
BreadCrump.js  {...rest is not resolving 

### ISSUE THREAD

**Issue by soorajshankar** [coreui/coreui-free-bootstrap-admin-template#294]
ERROR in ./src/components/Breadcrumb/Breadcrumb.js
Module build failed: SyntaxError: Unexpected token (21:26)

  19 | };
  20 |
> 21 | const BreadcrumbsItem = ({...rest, match}) => {
     |                           ^
  22 |   const routeName = findRouteName(match.url);
  23 |   if (routeName) {
  24 |     return (

 @ ./src/containers/Full/Full.js 25:18-57
 @ ./src/index.js

**Comment by c316** [comment]
https://webpack.js.org/loaders/babel-loader/

You need to add this line to the webpack.config.js file

```
              plugins: [require('babel-plugin-transform-object-rest-spread')]
```

So it will look like this

```
              use: {
                loader: 'babel-loader',
                options: {
                  cacheDirectory: true,
                  presets: ['react', 'env'],
                  plugins: [require('babel-plugin-transform-object-rest-spread')]
                }
              }
```
