### ISSUE TITLE
sidebar-minimized and brand-minimized toggle

### ISSUE THREAD

**Issue by dacodekid** [coreui/coreui-free-bootstrap-admin-template#301]
Because the `app.js` file is not checking the state a class but just toggles it..., if an app starts with `sidebar-minimized` class, then then `brand-minimized` actually reverse it.  

As a temporary fix, I currently toggle it during start-up, like below.

```js
$(document).ready(function($) {
    $('body').toggleClass('brand-minimized');
    resizeBroadcast();
});

```

**Comment by murliatdure** [comment]
<button class="sidebar-minimizer navbar-toggler aside-menu-toggler" type="button"></button>
