### ISSUE TITLE
Tabs with Dropdown is not working

### ISSUE THREAD

**Issue by murliatdure** [coreui/coreui-free-bootstrap-admin-template#303]
It worked for the first time then next time click is not responding in theme!

**Comment by murliatdure** [comment]
![image](https://user-images.githubusercontent.com/7137859/32987983-fb2e86a6-cd1f-11e7-9d60-4c03b30bf277.png)

**Comment by datasmithtech** [comment]
I also found this issue, and forums state this is an angular 5 issue.
it would have been better to create new repo for angullar 5 version, since angular 4 version probably would be working without this issue

**Comment by suleodu** [comment]
How can we now fix this in agular5

**Comment by xidedix** [comment]
Hi everyone, 
please make sure you are working with current version of **CoreUI-Angular** located here:
[https://github.com/mrholek/CoreUI-Angular](https://github.com/mrholek/CoreUI-Angular)
and open version specific issues here:
[https://github.com/mrholek/CoreUI-Angular/issues](https://github.com/mrholek/CoreUI-Angular/issues)
