### ISSUE TITLE
Composer package

### ISSUE THREAD

**Issue by DjustinK** [coreui/coreui-free-bootstrap-admin-template#31]
I noticed that there isn't a composer package for the coreui.
Could you create one so i and other can easily keep track of the updates?

**Comment by patkar** [comment]
How would a composer package help? Just curious :)

**Comment by o-log** [comment]
Sometimes it's convinient to install static coreui via composer (php package manager).

Now one have to register a package in his project composer.json like this:
```
  "repositories": [
    {
      "type":"package",
      "package": {
        "name": "mrholek/CoreUI-Free-Bootstrap-Admin-Template",
        "version":"1.0",
        "source": {
          "url": "https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template",
          "type": "git",
          "reference":"master"
        }
      }
    }
  ]
"require": {
    "mrholek/CoreUI-Free-Bootstrap-Admin-Template": "1.*",
}
```

If you add composer.json to repo the dependency will become much simplier:
```
  "repositories": [
    {
          "url": "https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template",
          "type": "git",
    }
  ]
"require": {
    "mrholek/CoreUI-Free-Bootstrap-Admin-Template": "1.*",
}
```

If you additionaly register the package at packagist.org - dependency will be as simple as:
```
"require": {
    "mrholek/CoreUI-Free-Bootstrap-Admin-Template": "1.*",
}

```

**Comment by patkar** [comment]
You should never use composer to install frontend packages. Use npm/yarn!
