### ISSUE TITLE
Split Bootstrap Styles from App Styles

### ISSUE THREAD

**Issue by bellwood** [coreui/coreui-free-bootstrap-admin-template#310]
Would it be possible to split the bootstrap and app styles in a future release to make managing the dependancies easier?

**Comment by marios-zindilis** [comment]
This is definitely a good idea. When everything works, it doesn't matter, but when trying to troubleshoot something or make a change, it's confusing to have Bootstrap and CoreUI styles mixed.

**Comment by bellwood** [comment]
Ideally CoreUI would include bootstrap and then apply its overrides in its own stylesheet.

**Comment by pelted** [comment]
Yup running into several small visual bugs and not having them separated is causing some real headaches.

**Comment by bellwood** [comment]
@mrholek any chance we could get some feedback on this please?

**Comment by mrholek** [comment]
We will consider it.

**Comment by nash-ye** [comment]
I am trying to use CoreUI standalone styles with separated Bootstrap, I can notice some UI changes!
@mrholek Does CoreUI uses a modified version of Bootstrap?
