### ISSUE TITLE
Wrong hrefs on read docs (angular)

### ISSUE THREAD

**Issue by ghost** [coreui/coreui-free-bootstrap-admin-template#313]
http://coreui.io/angular/

`<a class="btn btn-outline-primary" href="/docs/getting-started/angular4-version/">Read documentation</a>`

^ Buttons im referring to (theres 2 of them)

The documentation hrefs on the buttons have wrong links 
`http://coreui.io/docs/getting-started/angular4-version/`
->
`http://coreui.io/docs/getting-started/angular5-version/`

**Comment by xidedix** [comment]
Nice catch @Sikarii - thank you!
