### ISSUE TITLE
Tooltip for the charts on the card widgets is cutting off

### ISSUE THREAD

**Issue by kitarafrei** [coreui/coreui-free-bootstrap-admin-template#32]
Hi!
First of all let me say thank you very much for your hard work, I really like the framework.
I'm having problems with the chart widgets, it is cutting off the tooltip when it reaches the edge of the card. I wonder if we need to add an `overflow: visible` somewhere... need help figuring it out! 
Thanks!

**Comment by mrholek** [comment]
Hi, it's chart.js problem. You have to add external tooltips. http://www.chartjs.org/docs/#advanced-usage-external-tooltips

I'm going to add external tooltips in future updates.

**Comment by kitarafrei** [comment]
Hi! Thank you for a quick response!!! I'll have it fixed! Thank you!

**Comment by kitarafrei** [comment]
Hi, I don 't quite get it, I understand how to enable but how do I enable bootstrap tooltip on it? Should I do like:
1) Add html for tooltip markup:
`<div id="chartjs-tooltip" class="tooltip tooltip-top" role="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>`

2) Add the text:
var customTooltips = function(tooltip) {
     var tooltipEl = $('#chartjs-tooltip');
     if (tooltip.body) {
        var innerHtml = [
          (tooltip.beforeTitle || []).join('\n'), (tooltip.title || []).join('\n'), (tooltip.afterTitle || []).join('\n'), (tooltip.beforeBody || []).join('\n'), (tooltip.body || []).join('\n'), (tooltip.afterBody || []).join('\n'), (tooltip.beforeFooter || [])
          .join('\n'), (tooltip.footer || []).join('\n'), (tooltip.afterFooter || []).join('\n')
        ];
        tooltipEl.find('#tooltip-inner').html(innerHtml.join('\n'));
      }
};

How do I initialize the tooltip so it can show? I think I'm missing something :/

Thanks!

**Comment by BadAllOff** [comment]
Same problem. Really annoying. Embarrassing bug.

**Comment by xidedix** [comment]
- CoreUI v2 import and use our `CustomTooltips`: https://github.com/coreui/coreui-free-bootstrap-admin-template/blob/112721fb4be70038e8eb808d27e65d19cb823310/src/js/src/main.js#L18
- CoreUI v3 import and use our `customTooltips`: https://github.com/coreui/coreui-free-bootstrap-admin-template/blob/0b810831d37bfeb9dc3357d8ccad5c70525a7903/src/js/main.js#L17
