### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Nixellion** [coreui/coreui-free-bootstrap-admin-template#341]
Hi!

It would be great to have a dark\night version of this theme, ideally by just changing css file.

**Comment by xidedix** [comment]
here it is: https://coreui.io/#live-preview

**Comment by james-tcc** [comment]
It looks great, but how do you enable it? the .c-dark-theme class appears to do nothing

**Comment by xidedix** [comment]
@james-tcc 
The dark theme works with coreui-pro.
