### ISSUE TITLE
How to override variables?

### ISSUE THREAD

**Issue by Mish325** [coreui/coreui-free-bootstrap-admin-template#344]
Hi,

I recently started to using CoreUI and I would like to create my own theme which matches with our logo colors. What is the best way to override or create a new theme? I tried overriding color variables and theme colors on style.scss. Is it a good way or are there any best way to do this?

**Comment by marchershey** [comment]
Add variables in **_core-variables.scss**

**Comment by mrholek** [comment]
In version 2.0.0 you can easily overwrite variables here: https://github.com/coreui/coreui-free-bootstrap-admin-template/blob/master/src/scss/_variables.scss

**Comment by mrfambo** [comment]
Where are the list of Variables we can override?

**Comment by mrfambo** [comment]
For anyone !!! You can see the Variables in styles.css start.
Just make the variable like this in scss
`$primary: red`
It will change the --primary in root of scss.
