### ISSUE TITLE
RTL Version is not ok

### ISSUE THREAD

**Issue by KraToS-zz** [coreui/coreui-free-bootstrap-admin-template#347]
![coreui_-_open_source_bootstrap_admin_template_-_2018-02-19_23 50 51](https://user-images.githubusercontent.com/48319/36395725-cecba10e-15cf-11e8-9ae3-9cf3d3f1d9a5.png)
i changed dir="rtl" in html file and its not ok, am i doing wrong ? or i have to customize rtl version ?

**Comment by mrholek** [comment]
We will fix it in v2.0.0

**Comment by KraToS-zz** [comment]
can you tell us about release date of v2.0.0 ?

**Comment by KraToS-zz** [comment]
im using v2.1.2 now, but when i set to rtl mode, in small size sidebars being weird, you can test it
