### ISSUE TITLE
dev server deep links

### ISSUE THREAD

**Issue by deejbee** [coreui/coreui-free-bootstrap-admin-template#348]
I'm using `npm run dev` and Router.mode: 'history' but I can't open a browser and go direct to a page other than / first.  I'm guessing its the server not configured to serve the index.html perhaps or something else I might be missing?

Thanks for the awesome template :)

**Comment by deejbee** [comment]
just as a follow up I noticed that webpack puts `app.js` in index.html:

`<script type="text/javascript" src="app.js"></script>` so it causes a 404 if I navigate direct to `http://localhost:8090/pages/login` for example.  not sure how to change it or if the web config can be changed?

**Comment by deejbee** [comment]
OK, update.  I dug around all the config stuff and looking at `/config/index.js` I changed line 29 which is `dev.assetsPublicPath` to ''/``

Now index.html has:
`<script type="text/javascript" src="/app.js"></script>`

which then works when doing a hard fresh or deep linking.

**Comment by miki996** [comment]
Thanks man i found your answer very helpful. It fixed the issue i had with the deep linking server error.

So i guess it links to and app.js file from the Node JS runtime library?

**Comment by deejbee** [comment]
no, it just ensure it always uses the app.js from the root of your app, that's all. nothing to do with the nodejs runtime
