### ISSUE TITLE
Font awesome 5

### ISSUE THREAD

**Issue by darkomtc** [coreui/coreui-free-bootstrap-admin-template#349]
Would be nice to see font awesome 5 icons soon.

**Comment by pzPat** [comment]
Agreed.

**Comment by xidedix** [comment]
to install & upgrade from 4 to 5 see:
https://fontawesome.com/how-to-use/js-component-packages
https://fontawesome.com/how-to-use/upgrading-from-4

**Comment by nmatias** [comment]
I don't know if this can help someone, but i install via npm the free fontawesome 5 package on my project and when a build the vendors, the compilation give me some errors related with the webfont files path. I do some change to the regex in the build/vendors.j to work:

> Original line 91:
const path = assetPath.replace(/\?.*/, '').replace(/\'|\"/, '')

> Modified line 91:
const path = assetPath.replace(/\?.*|\#.*/, '').replace(/['"]/g, '')

I hope i help someone.

**Comment by mgsmus** [comment]
This is how I successfully installed Font Awesome 5:


1. Remove v4 and install v5
```
npm remove font-awesome
npm install @fortawesome/fontawesome-free
```

2. Edit vendor.js:92
https://github.com/coreui/coreui-free-bootstrap-admin-template/blob/c31b402c6e594110ead3984bea78c1216cc30dcb/build/vendors.js#L92

replace with
```
const path = assetPath.replace(/\?.*|#.*/, '').replace(/\'|\"/, '')
```

3. Update **all html files** in /src
https://github.com/coreui/coreui-free-bootstrap-admin-template/blob/c31b402c6e594110ead3984bea78c1216cc30dcb/src/404.html#L23

replace with:

```
<link href="node_modules/@fortawesome/fontawesome-free/css/all.min.css"> 
```

then
```
npm run build
```
