### ISSUE TITLE
ASP MVC version

### ISSUE THREAD

**Issue by weedkiller** [coreui/coreui-free-bootstrap-admin-template#350]
Hi, can you let us know if you will release regular and pro versions of ASP MVC 5

**Comment by mrholek** [comment]
Hi please check this repo [ASP.NET Core 2 MVC Version](https://github.com/mrholek/CoreUI-NET)

**Comment by weedkiller** [comment]
Hi I was looking for ASP MVC 5 version, I see you have paid versions too... wondering what we get with those in addition

**Comment by xidedix** [comment]
We are not sure if there is sufficient interest in version ASP MVC 5 since .NET Core emerge.

**Comment by cocowalla** [comment]
Plus, CoreUI is all about the front end - given the ASP.NET Core MVC template, it would take very little effort to make it work with MVC 5, for the few that really want it.

**Comment by xidedix** [comment]
We are considering the possibility actually.

**Comment by mvelosop** [comment]
Hi, I just published and updated post: [Building elegant applications with ASP.NET Core MVC 2.1 and CoreUI 2 (Bootstrap 4)](http://www.coderepo.blog/posts/building-elegant-applications-aspnet-core-mvc-2.1-coreui-2-bootstrap-4/)

**Comment by mach37** [comment]
@mvelosop I think this is much better than many of the other templates.. I had to update the nugets, its much faster. However I found it was deadlocking here... as in picture below

![image](https://user-images.githubusercontent.com/12221440/49185025-a8ffcf80-f315-11e8-9a9f-9106e724d2e0.png)

Using the `view tag helpers` also made your code more seamless to write..
