### ISSUE TITLE
CoreUI-Pro

### ISSUE THREAD

**Issue by luposky** [coreui/coreui-free-bootstrap-admin-template#352]
Not sure if this is the proper way to communicate, but I have some questions about coreui-pro ... 

I see the this free version is currently at 1.0.10 upgraded with the latest release of bootstrap 4, but coreui-pro is stuck at 1.0.8 with bootstrap beta 3 ... I'm missing something ?

There is a specifically support forum for the pro version ? I see a "premium support" item in the "CoreUI vs CoreUI PRO" web page, but no information on how to access it ...

I think Core-UI is a great product, I do not want to criticize but just have some more information.

**Comment by Qrzysio** [comment]
Three likes, no reply...

**Comment by mrholek** [comment]
Hi, we're working on version 2.0.0. We're going to release final version next week, both free and pro version

**Comment by Qrzysio** [comment]
> next week
Hopefully this week...

**Comment by imcodingideas** [comment]
Following as I was just considering buying the pro..

**Comment by Qrzysio** [comment]
Just to update. Should be like this:

> Hi, we're working on version 2.0.0. We're going to release final version ~~next week~~ next month, both free and pro version
