### ISSUE TITLE
Open links from inside "views" pages?

### ISSUE THREAD

**Issue by orishi** [coreui/coreui-free-bootstrap-admin-template#353]
Hello,
I've bought CoreUI Pro and I'm not sure how to make links to another page from inside views/page.

Pace is loading views pages perfectly (from navbar/sidebar), however, inside one of those opened pages (for example views/main.php), I want to make button which should redirect me to other page (for example views/second.php). I do not understand how to do that with pace? It should change to browser url to #second and load the page.

Also, can I send variables for $_GET?

What changes do I need to make?

Also, from navbar I link to "test.php", browser is redirected to "#test.php". Is it possible to hide the ".php"?

Thank you.

**Comment by marchershey** [comment]
Ugh.. i need this answered. If I find an answer, I'll let you know!
