### ISSUE TITLE
Steps for integrating CoreUI Pro Vue with Laravel

### ISSUE THREAD

**Issue by charitablehumans** [coreui/coreui-free-bootstrap-admin-template#355]
I'm desperately attempting to integrate the CoreUI Pro admin theme with Laravel but haven't the slightest clue as to how to accomplish this. If anyone could help or get me started that would be incredibly helpful.

**Comment by raduladans** [comment]
I am in the same situation as you. Have you managed to do it?

**Comment by charitablehumans** [comment]
Thank you ;)
