### ISSUE TITLE
Breadcrumb - Fixed position with responsive design artefacts

### ISSUE THREAD

**Issue by amno1** [coreui/coreui-free-bootstrap-admin-template#363]
Hi guys, I wanted to remove main navbar and to use the breadcrumb on main page as kind of a fixed navbar but I have an issue with it when horisontal size is small. There seems to be some interest in keeping breadcrumb fixed since I have found an old issue [#214 (and solution) ](https://www.google.se/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiZlI3i2K_aAhWia5oKHSboDjoQFggoMAA&url=https%3A%2F%2Fgithub.com%2Fmrholek%2FCoreUI-Free-Bootstrap-Admin-Template%2Fissues%2F213&usg=AOvVaw0Q_bu67wtCCSQRP1oK1pmH)which by now is closed. 

What I did tthe o original solution as implemented in #214, is changed CSS to not
add any margin on top, and it works for me, I get the looks and behaviour as I want when I scroll the page: ![Seen in a screenshot here:](https://user-images.githubusercontent.com/7167943/38558268-7604b532-3cc7-11e8-8153-f2031ffff2e8.png)

The problem is when horisontal size is reduced. As layout changes to accomodate for change,
the breadcrumb slides down for quite few pixels, and due to it's z-value it cover components below when the view is scrolled. The effect is seen here:

![breadcrdump2](https://user-images.githubusercontent.com/7167943/38558400-debbf7ac-3cc7-11e8-835d-069fc824de98.png)

I was lookiing in style.css to fix it but I don't seem to be able to find where it is defined for small sizes.
Any suggestion where to look or how to fix this?

My changes to breadcrumb-fixed style:

```
.breadcrumb-fixed .main {
  /* padding-top: 3.875rem; */
}

.breadcrumb-fixed .breadcrumb {
  position: fixed;
  /* top: 55px; */
  right: 0;
  left: 0;
  z-index: 1017;
}
```
And I also had to add a spacer to push form below the breadcrumb:

```
div.spacer {
  font-size: 0;
  height: 50px;
  line-height: 0;
}
```

**Comment by mvelosop** [comment]
Hi @amno1, this is not part of this codebase, so I just can't help you directly, but what I usually do is use the browser's developer tools ([F12] mostly) to trace the styles hierarchy and find the responsible one.

Hope that helps!

**Comment by amno1** [comment]
Yeah, you are right.


I will take another look at it tomorrow. Thanks!


________________________________
Från: Miguel Veloso <notifications@github.com>
Skickat: den 10 april 2018 16:43
Till: coreui/coreui-free-bootstrap-admin-template
Kopia: amno1; Mention
Ämne: Re: [coreui/coreui-free-bootstrap-admin-template] Breadcrumb - Fixed position with responsive design artefacts (#363)


Hi @amno1<https://github.com/amno1>, this is not part of this codebase, so I just can't help you directly, but what I usually do is use the browser's developer tools ([F12] mostly) to trace the styles hierarchy and find the responsible one.

Hope that helps!

**Comment by mvelosop** [comment]
I suggest you use the browser's developer tools to trace the style hierarchy to find the responsible one.

![image](https://user-images.githubusercontent.com/7357806/38564148-6e625c9e-3cd6-11e8-89d6-ef9dc0696924.png)

**Comment by amno1** [comment]
Indeed. That is great tip, thank you very much!

I have to admit I am a c/c++/java guy who has to do some quick html/css stuff :-).  I will look more at it tomorrow. If I find solution I will post it in the posted issue.


________________________________
Från: Miguel Veloso <notifications@github.com>
Skickat: den 10 april 2018 16:47
Till: coreui/coreui-free-bootstrap-admin-template
Kopia: amno1; Mention
Ämne: Re: [coreui/coreui-free-bootstrap-admin-template] Breadcrumb - Fixed position with responsive design artefacts (#363)


I suggest you use the browser's developer tools to trace the style hierarchy to find the responsible one.

[image]<https://user-images.githubusercontent.com/7357806/38564148-6e625c9e-3cd6-11e8-89d6-ef9dc0696924.png>

[https://user-images.githubusercontent.com/7357806/38564148-6e625c9e-3cd6-11e8-89d6-ef9dc0696924.png]

**Comment by amno1** [comment]
This is really driving me crazy. I can see that position changes when media
goes from large to md (to 992). And then postion-top changes to 55. I have
checked all possible css files and couldn't get what does this calculation.
I suspect that it may be some javascript file that calculates it, but I have no idea.
Anyway, if it is of public interest, I hacked it by brute force and changed _breadcrumb.scss in node_modules/bootstrap/scss

```
.breadcrumb {
  display: flex;
  flex-wrap: wrap;
  padding: $breadcrumb-padding-y $breadcrumb-padding-x;
  top: 0;
  margin-bottom: $breadcrumb-margin-bottom;
  list-style: none;
  background-color: $breadcrumb-bg;
  @include border-radius($border-radius);
}
```
Now it works at all sizes, the breadcrumb stayes on top and acts as a sortof navbar but 
just for the main element of the page.

**Comment by amno1** [comment]
I also realize it was part of core-ui not of core-ui boostrap template :-) sorry for that.

**Comment by mvelosop** [comment]
Just for fun, can you post the html + css (before the fix) somewhere?

**Comment by amno1** [comment]
css before:
```
.breadcrumb {
  display: flex;
  flex-wrap: wrap;
  padding: $breadcrumb-padding-y $breadcrumb-padding-x;
  margin-bottom: $breadcrumb-margin-bottom;
  list-style: none;
  background-color: $breadcrumb-bg;
  @include border-radius($border-radius);
}

Html before, I don't have it any more, but check the repo.
Html after:
```
<body class="app sidebar-fixed aside-menu-fixed sidebar-lg-show breadcrumb-fixed">
    
    <div class="app-body">
      <div class="sidebar">
        <nav class="sidebar-nav">
          <ul class="nav">
            <li class="nav-item">
              <a class="nav-link" href="index.html">
                <i class="nav-icon icon-speedometer"></i> Control Panel
              </a>
            </li>
            <li class="nav-title">Actions</li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <i class="nav-icon icon-drop"></i> Add Customer</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <i class="nav-icon icon-pencil"></i> Add Factory</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <i class="nav-icon icon-pie-chart"></i> Remove Customer</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <i class="nav-icon icon-pie-chart"></i> Remove Factory</a>
            </li>
            <li class="divider"></li>
            <li class="nav-title">Statistics</li>
            <li class="nav-item">
              <ul class="nav">
                <li class="nav-item">
                  <a class="nav-link" href="#" target="_top">
                    <i class="nav-icon icon-star"></i> Info Page 1</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#" target="_top">
                    <i class="nav-icon icon-star"></i> Info Page 2</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#" target="_top">
                    <i class="nav-icon icon-star"></i> Info Page 3</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#" target="_top">
                    <i class="nav-icon icon-star"></i> Info Page 4</a>
                </li>
              </ul>
            </li>
            <li class="nav-item mt-auto">
              <a class="btn" href="#">
                <i class="icon-logout"></i>  Logout</a>
            </li>
          </ul>
        </nav>
        <button class="sidebar-minimizer brand-minimizer" type="button"></button>
      </div>
      <main class="main">
        
        <ol class="breadcrumb ">
          <li class="breadcrumb-item"> Home</li>
          <li class="breadcrumb-item">
            <a href="#"> Admin</a>
          </li>
          <li class="breadcrumb-item active"> Dashboard</li>
          
          <li class="breadcrumb-menu d-md-down-none">
            <div class="btn-group" role="group" aria-label="Button group">
              <a class="btn" href="#">
                <i class="icon-speech"></i>
              </a>
              <a class="btn" href="./">
                <i class="icon-graph"></i>  Dashboard</a>
              <a class="btn" href="#">
                <i class="icon-settings"></i>  Settings</a>
              <a class="btn" href="#">
                <i class="icon-logout"></i>  Logout</a>
            </div>
          </li>
        </ol>
    <div class="container-fluid">

      <div class="spacer"></div>
```
I have just clone core-ui repo, I am looking where to add my change so I can push everything to my github. I am not sure what files are involved, but that above is what gets my breadcrumb stick on top.

**Comment by amno1** [comment]
So it was app-body margin :-). Thank you.

Yeah I have removed header, I called it "main navbar" in my original post.  As I said I couldn't find what css part was responsible for computation, so I used brute force and changed breadrumbs css as I described above, setting top to 0. I suppose it workes in all media queries . I did have to compensate in my "spacer" div to keep form below the breadcrumb, and I have two different css for spacer, one for < 922 pixels and one for >922:
```
div.spacer{
    font-size: 0;
    line-height: 0;
}
@media (max-width: 991.98px) {
  div.spacer {
    height: 5px;
  }
}
@media (min-width: 991.98px) {
  div.spacer {
    height: 70px;
  }
}
```
I guess your solution is better than since you don't need to compensate with spacer.

**Comment by amno1** [comment]
I tested your solution, but I still needed a spacer to push my form below the breadcrumb, but now I can use same css for all sizes. I have also app-body margin as 0 for all sizes, works fine spacer height 70 for all sizes.

**Comment by amno1** [comment]
And final touch to breadcrumb:
  `align-items: center;`

**Comment by mvelosop** [comment]
I didn't looked at the form, but may be instead of the spacer you could add a margin-top: 70px style to the form div, maybe something like **div > form { margin-top: 70px; }** if it applies to all forms, so you save having to add the div.spacer everywhere.

**Comment by mvelosop** [comment]
or **div.xxx > form {**...

**Comment by amno1** [comment]
No, just one spacer is needed to push down main body below the breadcrumb. It's not needed elsewhere. I tested.

**Comment by suchetaswabhav** [comment]
@amno1 ...  i want to ask ...is your code for 3 level breadcrumb or two level breadcrumb ?

**Comment by suchetaswabhav** [comment]
can you put the whole code for three - level breadcrumb please
