### ISSUE TITLE
Close navigation dropdown links when open other dropdownlinks

### ISSUE THREAD

**Issue by prakash403** [coreui/coreui-free-bootstrap-admin-template#364]
Hello,

I am using Core Ui, in the Sidebar navigation component when i open the dropdown links are open with child components Menwhile  open other l dropdown links then before link is open , How can we close other links when i open new links.

**Comment by felix-voicehub** [comment]
I am also looking for this in the Vue version of coreui.

**Comment by rasponline** [comment]
Me too for Vue version. Did you get any workaround so far ?

**Comment by mrholek** [comment]
Hi, this feature should be available in CoreUI 3
