### ISSUE TITLE
I think this doesn't look too good!

### ISSUE THREAD

**Issue by mvelosop** [coreui/coreui-free-bootstrap-admin-template#366]
Hi @mrholek, I think this doesn't look nice but, since it's obviously a matter of personal taste I didn't want to rush "fixing" anything, because that's exclusively your call!

![image](https://user-images.githubusercontent.com/7357806/38705040-20f18c7a-3ea0-11e8-8634-3c4a5489e8b2.png)

**Comment by mrholek** [comment]
Which version of @coreui/coreui you have in package.json

**Comment by mvelosop** [comment]
It's 2.0.0-beta-1 https://github.com/mvelosop/coreui-free-bootstrap-admin-template/blob/dev/package.json

**Comment by mvelosop** [comment]
Great!
