### ISSUE TITLE
Would you handle an alternative form to arrange vendors folder?

### ISSUE THREAD

**Issue by mvelosop** [coreui/coreui-free-bootstrap-admin-template#367]
Hi @mrholek, I feel a little uneasy about copying same-type files from different vendors in the same folder on building the distribution version (e.g. copying .js files from different vendors in the same **/dist/vendors/js** folder), because it might cause some conflict in case two vendors settle for the same filename.

Besides that, the convention used by the ASP.NET MVC Core standard template is having a lib folder that keeps the node_modules file structure for each vendor (e.g. **/lib/jquery-validation/dist/jquery.validate.min.js**), so, if CoreUI had this folder structure it would be much easier to use ready-made compiled views (for account and user management) from the ASP.NET Core team with CoreUI.

So, the questions is, would you take in a PR that adds an option to **package.json**, e.g. something like **build-aspnetcore**, to handle this alternate way to organize the vendors folder?

TIA.

**Comment by mvelosop** [comment]
Hey, I just stumbled with a good candidate for naming conflicts: **node_modules/jquery-validation/dist/localization/messages_es.js**

**Comment by mvelosop** [comment]
Just in case I wasn't clear enough, I'd do the PR! ;-)

**Comment by mrholek** [comment]
I think it's good idea. We have to rewrite build/vendors.js to achive this.

**Comment by mvelosop** [comment]
Yep, I'll do it!

**Comment by mrholek** [comment]
We're going to release 2.0.0 this week and I'm completely snowed under. I will check it later this week, ok?

**Comment by mach37** [comment]
@mvelosop any update on the ASP version
