### ISSUE TITLE
Suggestion for Register page

### ISSUE THREAD

**Issue by mvelosop** [coreui/coreui-free-bootstrap-admin-template#369]
Hi @mrholek ,

I think the register page is a bit limited regarding the external login options, as it now only handles two nicely.

May be placing the external logins to the right could make room for more options.

![image](https://user-images.githubusercontent.com/7357806/38733395-963a5d94-3f19-11e8-850f-c6d5d34462cf.png)

TIA.

**Comment by marchershey** [comment]
...or you can just change the twitter button to a gray "more" button and have a modal with all the social logins you want, which is exactly what I do.
