### ISSUE TITLE
Angular2+ AOT build giving error!

### ISSUE THREAD

**Issue by shajeeck** [coreui/coreui-free-bootstrap-admin-template#374]
Angular2+ AOT build `ng build --prod` is giving error 

> ERROR in Error during template compile of 'AppModule'
>   Function calls are not supported in decorators but 'AppBreadcrumbModule' was called.

To regenerate

1. Download angular2+ template branch
1. npm i
1. ng build --prod

Any workaround?

**Comment by mrholek** [comment]
Hi, we're working on this issue.

BTW This is not angular version repository, here is proper repository: https://github.com/coreui/coreui-free-angular-admin-template
