### ISSUE TITLE
Licensing for open source CMS

### ISSUE THREAD

**Issue by lane711** [coreui/coreui-free-bootstrap-admin-template#377]
Hi, awesome theme!

I'm intersted in using it for an open source nodejs/vue based CMS. I'd be using it for the admin area of the site. Is this possible giving your licensing terms?

Thanks

**Comment by Rockstar04** [comment]
The license is a standard MIT license. https://github.com/coreui/coreui-free-bootstrap-admin-template/blob/master/LICENSE
