### ISSUE TITLE
What's the difference between all of your repos?

### ISSUE THREAD

**Issue by marchershey** [coreui/coreui-free-bootstrap-admin-template#380]
Which one is the correct repo to use?

I'm guessing this is just the HTML version?

**Comment by mvelosop** [comment]
Just check the readme!

**Comment by marchershey** [comment]
First of all, if all of your links worked in the readme, that would help. 

Second of all, they are not all updated at the same time. For example, this repo is clearly updated more often then lets say the Ajax version is. That is why I ask this question.

How often are the other versions updated?

**Comment by Qrzysio** [comment]
Use the standard static HTML version. Ajax version is different in the way of creating links that navigate you in the panel. Check out demos, you will see the difference.
