### ISSUE TITLE
Weird SideBar

### ISSUE THREAD

**Issue by FlowUpMedia** [coreui/coreui-free-bootstrap-admin-template#389]
So i cloned this repo today, and did all the steps right ever repeated it 2 times and i found this things:

**Here is all ok no problems right? Now check the others**
![ok](https://user-images.githubusercontent.com/37281910/39974053-ef0d53a6-571d-11e8-92f5-b5121f6e88c3.png)

**When i put the mouse hover the scroll bar this happen, i can the the big one and another behind it weird**
![ok2](https://user-images.githubusercontent.com/37281910/39974054-ef33bfb4-571d-11e8-8277-1531ad7876e6.png)

**When i Shrink the page this happens, even more weird**
![ok3](https://user-images.githubusercontent.com/37281910/39974055-ef513224-571d-11e8-8d37-35fe0560cc98.png)

**When i only put the icons with that button on the bottom, this happens but there is no reason for that**
![ok4](https://user-images.githubusercontent.com/37281910/39974056-ef700226-571d-11e8-8ee1-9847985b68e5.png)

**Here if you have 4 or more items on the dropdown you can only see 3**
![ok5](https://user-images.githubusercontent.com/37281910/39974057-ef8c3964-571d-11e8-9fd5-72966099e04c.png)

**Comment by mrholek** [comment]
When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Reduced test cases and potential fixes using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)
