### ISSUE TITLE
Get Overloaded css stylesheet without scss

### ISSUE THREAD

**Issue by andryshok** [coreui/coreui-free-bootstrap-admin-template#390]
How to receive separately the file css, separately from most bootstrap?
Example
 ```
<link href="css/bootstrap.min.css" rel="stylesheet">
 <link href="css/style.css" rel="stylesheet">  -- this is overload main bootstrap css
```

**Comment by mrholek** [comment]
We don't use bootstrap css files, because we use custom variables and overwrite bootstrap styles. So you should use only our styles.

**Comment by andryshok** [comment]
It is bad as won't allow to receive timely updates in case of a release of the new version bootstrap
