### ISSUE TITLE
Errors while installing and trying to run serve

### ISSUE THREAD

**Issue by honeyfairy** [coreui/coreui-free-bootstrap-admin-template#393]
SYSTEM: CENTOS7 64BIT LATEST

[root@adminpaneltest my-project]#  npm install
npm ERR! registry error parsing json
npm WARN deprecated uws@9.14.0: stop using this version
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN prefer global node-gyp@3.7.0 should be installed with -g

> uws@9.14.0 install /root/my-project/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

[root@adminpaneltest my-project]# npm run serve

> @coreui/coreui-free-bootstrap-admin-template@2.0.0 serve /root/my-project
> npm-run-all --parallel localhost watch-css watch-js

> @coreui/coreui-free-bootstrap-admin-template@2.0.0 localhost /root/my-project
> browser-sync start --server "./src" --serveStatic "./" --files "!./src/js/src/**/*, ./src/**/*, !./src/scss/**/*"

> @coreui/coreui-free-bootstrap-admin-template@2.0.0 watch-css /root/my-project
> nodemon --ignore dist/ -e scss -x "npm run css"

> @coreui/coreui-free-bootstrap-admin-template@2.0.0 watch-js /root/my-project
> nodemon --watch src/js/src/ -x "npm run js"

[nodemon] 1.17.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `npm run css`
[nodemon] 1.17.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /root/my-project/src/js/src/**/*
[nodemon] starting `npm run js`

> @coreui/coreui-free-bootstrap-admin-template@2.0.0 css /root/my-project
> npm-run-all --parallel css-compile* --sequential css-prefix css-minify*

> @coreui/coreui-free-bootstrap-admin-template@2.0.0 js /root/my-project
> npm-run-all --parallel js-compile* js-lint*

[Browsersync] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://45.32.180.139:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://45.32.180.139:3001
 --------------------------------------
[Browsersync] Serving files from: ./src
[Browsersync] Watching files...
[Browsersync] Couldn't open browser (if you are using BrowserSync in a headless environment, you might want to set the open option to false)

> @coreui/coreui-free-bootstrap-admin-template@2.0.0 css-compile /root/my-project
> node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 src/scss/style.scss src/css/style.css

> @coreui/coreui-free-bootstrap-admin-template@2.0.0 css-compile-vendors /root/my-project
> node build/vendors-sass.js

> @coreui/coreui-free-bootstrap-admin-template@2.0.0 js-compile /root/my-project
> cross-env PLUGINS=true babel src/js/src/ --out-dir src/js/ --source-maps

> @coreui/coreui-free-bootstrap-admin-template@2.0.0 js-lint /root/my-project
> eslint src/js/src

fs.js:961
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/root/my-project/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:961:18)
    at Object.getInstalledBinaries (/root/my-project/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/root/my-project/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/root/my-project/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/root/my-project/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/root/my-project/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/root/my-project/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)

npm ERR! Linux 3.10.0-862.3.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "run" "css-compile"
npm ERR! node v6.14.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @coreui/coreui-free-bootstrap-admin-template@2.0.0 css-compile: `node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 src/scss/style.scss src/css/style.css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @coreui/coreui-free-bootstrap-admin-template@2.0.0 css-compile script 'node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 src/scss/style.scss src/css/style.css'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @coreui/coreui-free-bootstrap-admin-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 src/scss/style.scss src/css/style.css
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @coreui/coreui-free-bootstrap-admin-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm bugs @coreui/coreui-free-bootstrap-admin-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @coreui/coreui-free-bootstrap-admin-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/my-project/npm-debug.log
ERROR: "css-compile" exited with 1.

npm ERR! Linux 3.10.0-862.3.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "css"
npm ERR! node v6.14.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @coreui/coreui-free-bootstrap-admin-template@2.0.0 css: `npm-run-all --parallel css-compile* --sequential css-prefix css-minify*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @coreui/coreui-free-bootstrap-admin-template@2.0.0 css script 'npm-run-all --parallel css-compile* --sequential css-prefix css-minify*'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @coreui/coreui-free-bootstrap-admin-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all --parallel css-compile* --sequential css-prefix css-minify*
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @coreui/coreui-free-bootstrap-admin-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @coreui/coreui-free-bootstrap-admin-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/my-project/npm-debug.log
[nodemon] app crashed - waiting for file changes before starting...
�  Successfully compiled 6 files with Babel.
[Browsersync] Reloading Browsers... (buffered 12 events)
[nodemon] clean exit - waiting for changes before restart

**Comment by xidedix** [comment]
Error: ENOENT: no such file or directory, scandir `/root/my-project/node_modules/node-sass/vendor`

please try `npm rebuild node-sass`
