### ISSUE TITLE
JQuery Not Working In Bootstrap Modal.

### ISSUE THREAD

**Issue by AkshatSrivastava2** [coreui/coreui-free-bootstrap-admin-template#396]
Error : $(...).modal('show') is not a function is shown in the console.

I am implementing modal and on clicking a button I have made call to a function and and in that function I have called for $('#exampleModal').modal('show').
The Modal is not getting Triggered.

**Comment by Emmarex** [comment]
Same thing here. Any fix ?

**Comment by AkshatSrivastava2** [comment]
@Emmarex Fix for me:
import 'jquery';
import 'bootstrap';
and installed bootstrap and jquery using npm.
