### ISSUE TITLE
CoreUI Alba to Bootstrap v4.1

### ISSUE THREAD

**Issue by cannect** [coreui/coreui-free-bootstrap-admin-template#397]
Hi,

Is it possible to convert the CoreUI Alba theme to Bootstrap 4.1? Is there an upgrade steps documentation available?

I do not think there is much changed in Alba versus default Bootstrap, so I wanted to know if there is a custom styles css with only the addional styling versus default Bootstrap. Or how to do it ourselves.

Thanks!

**Comment by xidedix** [comment]
Hi @cannect 
We are working on this.

**Comment by mikewindow** [comment]
Is the Bootstrap 4.5.x update of the alba theme still in progress?

**Comment by mikewindow** [comment]
Also see https://github.com/coreui/coreui-react/issues/57

**Comment by mikewindow** [comment]
https://github.com/coreui/coreui-react/issues/57 is related

**Comment by mikewindow** [comment]
https://github.com/coreui/coreui-free-bootstrap-admin-template/issues/233 is related

**Comment by mikewindow** [comment]
Support site thread https://community.coreui.io/t/alba-theme-update-to-bootstrap-4/40
