### ISSUE TITLE
Is it possible to remove the hash #! from the URL? Attempted to use LocationProvider..

### ISSUE THREAD

**Issue by zachcoss** [coreui/coreui-free-bootstrap-admin-template#399]
Hi!

I'm using the AngularJS CoreUI template, and trying to remove the (#!) from the url. Attempted to use:

$locationProvider.html5Mode(true);

within both the src/routes.js and src/demo/routes.js but it prevents the page from loading (says that the $locationProvider could not be injected):

Failed to instantiate module app due to:
TypeError: $locationProvider.html5Mode is not a function

Is this the right way to remove the hash? Am I missing something? I added the base tag to the index page, still didn't work.

Thanks!!

**Comment by mohamed-alashry** [comment]
did you find anything?
