### ISSUE TITLE
Left Menu Does not Show Right Expand Chevron on Small Devices

### ISSUE THREAD

**Issue by sansagara** [coreui/coreui-free-bootstrap-admin-template#402]
This is a styling issue.
The left nav menu has a feature where you can click a small chevron icon on the bottom to show only the icons. If you do that on a small screen computer, the right chevron (expand) is not shown, and you can not scroll the options to the bottom. So basically, you need to reload the page.

![image](https://user-images.githubusercontent.com/1382235/42540853-a72b6c42-8465-11e8-8c41-e8e10db932a5.png)

**Comment by xidedix** [comment]
fixed in `v2.1.3` or update `@coreui/coreui` to `2.0.9` in dependencies
- please let us know if that works for you

**Comment by sansagara** [comment]
That did the trick @xidedix 
Note that my project used coreui-pro  but updating to the latest version also did the trick.
