### ISSUE TITLE
Minimizing sidebar with bottom chevron does not allow to maximize it again

### ISSUE THREAD

**Issue by ivansammartino** [coreui/coreui-free-bootstrap-admin-template#404]
Hello,
When using Google Device Toolbar (or any small / medium screen device), minimizing the sidebar with the bottom chevron can not be reverted: it is forever, and the whole page must be reloaded to maximize sidebar again

Please see attached zipped video
[core-ui-bug.zip](https://github.com/coreui/coreui-free-bootstrap-admin-template/files/2216198/core-ui-bug.zip)

Thanks

- Windows 10
- Chrome latest version

**Comment by buddyy93** [comment]
is there any updates for this ?

**Comment by xidedix** [comment]
fixed in `v2.1.3` or update `@coreui/coreui` to `2.0.9` in dependencies
- please let us know if that works for you
