### ISSUE TITLE
sidebar-sm-show

### ISSUE THREAD

**Issue by rharor** [coreui/coreui-free-bootstrap-admin-template#408]
When I leave the default `<body class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show">` everything works great. However I want the sidebar to appear by default on sm or larger. So I followed the instructions(https://coreui.io/docs/components/sidebar/) to change it 
`<body class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-sm-show">`

This appears to work at first glance. However, unlike `sidebar-lg-show`, for `sidebar-sm-show` the sidebar toggle button does not work. If I resize the window to larger or smaller, then the toggle works and I can go back to sm size and the toggle works. But onload the toggle does not work on sm. This isn't the same behaviour on `sidebar-lg-show` where the toggle works onload.

This seems like a bug to me. I have tried to search for this but did not find anything. I'm using Chrome(Version 68.0.3440.84 (Official Build) (64-bit)) on Windows 10. I downloaded the latest version of CoreUI 5 minutes ago to try it on a new project.

**Comment by xidedix** [comment]
hr @rharor 
try to modify sidebar toggler button from `data-toggle="sidebar-lg-show"` to `data-toggle="sidebar-sm-show"` and its `display` property accordingly (as well as mobile sidebar toggler button display property, to make sure they not interfere)
