### ISSUE TITLE
On Mobile  Menu not dismissed When link clicked

### ISSUE THREAD

**Issue by aaronfhd** [coreui/coreui-free-bootstrap-admin-template#409]
When Clicking on a menu item on mobile the menu is not dismissed. I have even tried this on your demo and it is the same thing. 

Is there a workaround on this.
Thanks.

**Comment by mentadev** [comment]
Any news on this? it is true, even on the demo the menu is not working on mobile devices.

**Comment by aaronfhd** [comment]
Any word on this?  Would like to know if there will be a fix.  Thanks.

**Comment by orbitrod** [comment]
I am also having the same issue.

**Comment by xidedix** [comment]
Are we talking about mobile sidebar?
What's your version of:
- @coreui/coreui-free-bootstrap-admin-template
- @coreui/coreui

**Comment by aaronfhd** [comment]
@coreui/coreui-free-bootstrap-admin-template

Even take a look at your demo.

https://coreui.io/demo/#main.html

When you are on a Mobile device the menu does not dismiss when a sidebar menu is clicked.

**Comment by xidedix** [comment]
The online demo needs to be updated - it's the older one. That's why I asked about your versions.

**Comment by aaronfhd** [comment]
<link rel="stylesheet" href="https://unpkg.com/@coreui/coreui/dist/css/coreui.min.css">
<script src="https://unpkg.com/@coreui/coreui/dist/js/coreui.min.js"></script>

Running the one all from your documentation

**Comment by xidedix** [comment]
please update your `@coreui/coreui` to `v2.0.6` and let us know is it any better

**Comment by aaronfhd** [comment]
Perfect, It works. 
Can you look into this please.
https://github.com/coreui/coreui-free-bootstrap-admin-template/issues/413
