### ISSUE TITLE
CoreUI Free .NET Core 2 Admin Template

### ISSUE THREAD

**Issue by mmalik76** [coreui/coreui-free-bootstrap-admin-template#414]
I wanted to see if there was an ETA for when the CoreUI Free .NET Core 2 Admin Template would be available. On the README is says "Available Soon" but just wanted to see if there was any idea how soon? I just figured I ask before I tried creating my own. Thanks.

**Comment by xidedix** [comment]
hi @mmalik76 
Please take a look at the blog post by Miguel Veloso: https://www.coderepo.blog/posts/building-elegant-applications-aspnet-core-mvc-2.1-coreui-2-bootstrap-4/
