### ISSUE TITLE
Thousands of files in node_modules folder

### ISSUE THREAD

**Issue by tsegato** [coreui/coreui-free-bootstrap-admin-template#418]
I followed the installation instructions. There are thausands and thousands of files and folders in the node_modules folder. My development environment freezes and it is impossible to work with.

![coreui](https://user-images.githubusercontent.com/43033640/45153328-d5eb8d00-b1d3-11e8-8aa5-b5be7cba3845.png)

Is this by design?

**Comment by xidedix** [comment]
hi @tsegato 
That's true. There is a `node_modules` directory with a  crazy large number of dependencies. Most of the files are necessary for dev tooling only. The others are client-side project dependencies - and they will be included with the final build.

As far as I understand, your IDE freezes with very slow project load times. What's your development environment and IDE name/version?

**Comment by xidedix** [comment]
@tsegato 
Please try to mark the `node_modules` folder as a hidden folder. This should effectively hide the directory from Visual Studio and Solution Explorer.

**Comment by tsegato** [comment]
Whats the best approach for getting only needed core files?

**Comment by xidedix** [comment]
@tsegato 
It's a Visual Studio issue. I wonder whether setting the hidden attribute on the `node_modules` folder helped you? -> Right click on `node_modules` -> Properties -> set `Hidden` attribute for the folder only.
`npm` should continue to work with the hidden folder, without side effect for actual package access.

**Comment by tsegato** [comment]
When I added the files they are added to the visual studio project file. So I need to wait for Visual Studio to finish removing them so they are removed from the project file to. Being waiting for 6 hours now, and still waiting :D I am an consultant and have multiple customers right now where this template is an option. I really like the look and feel of the template. But I cant justify to have more than 20.000 files for a simple admin dashboard. To much for versioning control, deployment etc. I cant just hide the folder, because some files are needed by the template. Bootstrap as an example. So is there anyway I can get a version with just the core files needed (the css, html and js) files? All other templates we are testing has a minimal set of files needed, I am sure same can be applied here?

**Comment by xidedix** [comment]
There must be some kind of misunderstanding I am afraid.  `npm` is node.js package manager used here as a dependency manager for the project. There is no need for versioning control or deployment of `node_modules`. Bootstrap, jquery etc, are included in the `dist` folder during the `build` process.  

VS 2017 hint: instead of `File -> Open -> Folder` use `File -> Open -> Web Site...` from now on the solution opens in no time

**Comment by tsegato** [comment]
I think we are getting closer. I am using this with MVC and I know Visual Studio. I think I am looking for the dist library. Sounds like that folder only contains core files. How do you build that folder? I only want the core js, css needed to build the web site. If you look at my image I dont have a dist folder. Is there any where you can download the dist folder?

**Comment by xidedix** [comment]
@tsegato 
`dist` directory is created with the `build` - see: https://github.com/coreui/coreui-free-bootstrap-admin-template#usage
You may be interested also in the blog post by Miguel Veloso: https://www.coderepo.blog/posts/building-elegant-applications-aspnet-core-mvc-2.1-coreui-2-bootstrap-4/

**Comment by tsegato** [comment]
Perfect that article helped building the dist folder, just perfect. Thanks for your support and patience.
