### ISSUE TITLE
No scrollbar on load

### ISSUE THREAD

**Issue by tsegato** [coreui/coreui-free-bootstrap-admin-template#419]
When loading the template first time and expanding some menus there is no scrollbar. This applies for both IE and Chrome. If I scroll down using touch screen the scrollbar appears and I can scroll down. But this means its not possible for users with a pc with no touch screen to scroll down in left navigation bar?
![coreui01](https://user-images.githubusercontent.com/43033640/45243067-bf882300-b2f2-11e8-9e91-461c0d00bbd7.png)

**Comment by mrholek** [comment]
You have screenshots from two differents version (1. CoreUI, 2 CoreUI Pro). CoreUI Pro has more element in sidebar that's why scrollbar is active.

Scrollbar should be active if height of navigation is bigger then height of sidebar, but something doesn't work at this moment. We have to check it.

**Comment by tsegato** [comment]
Thanks let me know when its ready. As soon as a got a working template I will buy the all frameworks license.

**Comment by mrholek** [comment]
We're going to fix this issue in next release. It will be ready this month.

**Comment by tsegato** [comment]
Any news here? Does the pro version have the issue too?

**Comment by CarlosGabrielTovar1991** [comment]
Can you make the same fix release for the React version? This has the same problem.

**Comment by stevedhs** [comment]
Has this been fixed?

**Comment by jtsmedley** [comment]
I don't think its been fixed.  The sidebar has been an issue for us for 2 years now.

**Comment by stevedhs** [comment]
Thanks for the reply @jtsmedley 
Is there anything you have done to manage it or you have left it as it is?, I am lost and in the middle of a project, was hoping this would be a simple fix . :/

**Comment by stevedhs** [comment]
I just used a div around the  Navbar with overflow as a work around :/ 
```
<div
                          className="animated fadeIn"
                          style={{ overflow: "auto" }}
                        > 
```
