### ISSUE TITLE
Top bar issues with IE11

### ISSUE THREAD

**Issue by ASKemp** [coreui/coreui-free-bootstrap-admin-template#421]
Seems to be layout issues with the top navigation bar in IE11 when resizing the window, the logo drops down to the next line. 

Also, on your website, the "Live preview", "Download CoreUI" and "Get a CoreUI Pro license" boxes are broken under IE

**Comment by xidedix** [comment]
hi @ASKemp - thanks for the heads up
please update `@coreui/coreui` to `2.0.10` in dependencies and us know if that works

**Comment by ASKemp** [comment]
Will check it out.
I assume I need to get the repo and build it to get the updated files since the download doesn't have the @coreui distribution.
On a related note, can I pull the @coreui files in directly to Visual Studio via library manager? 
All new to me - many thanks.
