### ISSUE TITLE
Where is the datetimepicker?

### ISSUE THREAD

**Issue by yelnyaface** [coreui/coreui-free-bootstrap-admin-template#422]
Datetimepicker do not exist in the FREE or Pro version at all,

So this theme does not even support datetimepicker?

**Comment by 1074Prasanth** [comment]
you may use input="date"

**Comment by C-BERBER** [comment]
Seriously ? Isn't that the default one? is there nothing a little better looking from COREUI?

**Comment by 1074Prasanth** [comment]
there is nothing like date picker in coreUi,If you want elegant date picker you may use calender in semantic ui.

**Comment by C-BERBER** [comment]
So they went to the trouble to do a range picker but not a single calendar version of it? I paid good money for the COREUI Pro... kinda figured that would be basic

**Comment by prathmesh28** [comment]
use  type="datetime-local"
