### ISSUE TITLE
Navbars slides in under IE

### ISSUE THREAD

**Issue by ASKemp** [coreui/coreui-free-bootstrap-admin-template#428]
The left hand navbar slides in/open on each page refresh under IE, doesn't do this under Chrome.

This is especially noticeable if loading a large page or data table, the left nav can 'stall' half way from sliding in whilst the page loads. Under Chrome its there on page load and just the swap from standard to slim scroll bar is waits for page load, which is fine.

**Comment by sholman** [comment]
I'm getting this as well.

**Comment by ASKemp** [comment]
This has been fixed for me in the latest updates.
