### ISSUE TITLE
key events not working

### ISSUE THREAD

**Issue by rahulreghunath** [coreui/coreui-free-bootstrap-admin-template#432]
Keyup and down events not working in text boxes

**Comment by 1074Prasanth** [comment]
can you elaborate or provide the code snippet(where you have strucked)

**Comment by rahulreghunath** [comment]
```
<b-form-input id="patients" @keyup="myFun "placeholder="Number Patients in Session"v-model.trim="form.patients">
</b-form-input>
``` 
no event gets triggered

**Comment by rutAshual** [comment]
I do not know the  framework in this job but in another framework  should put brackets in the function call
