### ISSUE TITLE
Issues on RTL

### ISSUE THREAD

**Issue by MrDevIr** [coreui/coreui-free-bootstrap-admin-template#433]
On RTL enabled if you scroll on sidebar the sidebar content will disappear (start to go right as you see in second snapshot left parameter is decreasing). if you click on any menu that has sub items before scrolling it will work fine.
It could be fixed by removing. don't know side effects ;)

```
 .sidebar .sidebar-nav {
    position: relative;
}
```

and also sidebar minimizer button position and direction is not correct should be vice versa.
![coreui](https://user-images.githubusercontent.com/12736825/46716738-10809380-cc72-11e8-9de0-edffca095508.PNG)

![coreui-flow](https://user-images.githubusercontent.com/12736825/46716746-17a7a180-cc72-11e8-9e3b-de191214b187.PNG)

- Win 10
- Chrome
- Coreui v2.1.5 (in style.css mentioned version v2.0.12)

**Comment by MrDevIr** [comment]
Still have the problem if minimize the sidebar and maximize it there is no problem! should I do something else other than:

> To enable RTL support you have to add dir="rtl" to html tag

also I found breadcrumb spacing is not right on rtl
my solution:
```
.breadcrumb-item+.breadcrumb-item::before { padding-left: .5rem; padding-right: 0;}
breadcrumb-item { padding-right: .5rem; padding-left: 0;}
```

**Comment by xidedix** [comment]
@MrDevIr 
please update `@coreui/coreui` to `^2.0.16` in `dependencies` and let us know is it any better with breadcrumbs padding and sidebar scrolling

**Comment by MrDevIr** [comment]
Thank you @xidedix it's fine now.
I'll work on sidebar minimizer.

**Comment by MrDevIr** [comment]
@xidedix fixed sidebar minimizer in rtl by:
```
[dir=rtl] body .sidebar .sidebar-minimizer:hover::before {
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 11 14'%3E%3Cpath fill='%2373818f' d='M1.7,2c0-0.1,0-0.3,0.1-0.4l1.3-1.3c0.1-0.1,0.2-0.1,0.4-0.1c0.1,0,0.3,0,0.4,0.1l5.8,5.8 c0.1,0.1,0.1,0.2,0.1,0.4s0,0.3-0.1,0.4l-5.8,5.8c-0.1,0.1-0.2,0.1-0.4,0.1c-0.1,0-0.3,0-0.4-0.1l-1.3-1.3c-0.1-0.1-0.1-0.2-0.1-0.4 s0-0.3,0.1-0.4L6,6.5L1.9,2.4C1.8,2.3,1.7,2.1,1.7,2z'/%3E%3C/svg%3E");
}

[dir=rtl] body .sidebar .sidebar-minimizer::before {
    right: unset;
    left: 0;
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 11 14'%3E%3Cpath fill='%23fff' d='M1.7,2c0-0.1,0-0.3,0.1-0.4l1.3-1.3c0.1-0.1,0.2-0.1,0.4-0.1c0.1,0,0.3,0,0.4,0.1l5.8,5.8 c0.1,0.1,0.1,0.2,0.1,0.4s0,0.3-0.1,0.4l-5.8,5.8c-0.1,0.1-0.2,0.1-0.4,0.1c-0.1,0-0.3,0-0.4-0.1l-1.3-1.3c-0.1-0.1-0.1-0.2-0.1-0.4 s0-0.3,0.1-0.4L6,6.5L1.9,2.4C1.8,2.3,1.7,2.1,1.7,2z'/%3E%3C/svg%3E");
}
```

**Comment by MrDevIr** [comment]
for card headers icon:
```
[dir=rtl] .card-header > i {
    margin-right: 0;
    margin-left: .5rem;
}
```

**Comment by xidedix** [comment]
Thanks for your help, @MrDevIr !
please verify with `@coreui/coreui`  updated to `^2.0.17`

**Comment by xidedix** [comment]
@MrDevIr - unpkg - no idea why :-| 
it's also there https://cdn.jsdelivr.net/npm/@coreui/coreui@2.0.19/
