### ISSUE TITLE
Cannot type in b-form-textarea

### ISSUE THREAD

**Issue by suevy** [coreui/coreui-free-bootstrap-admin-template#444]
> Issue in VUE.js project.
> Version: 2.0.2

In HTML:
```
<template>
<b-form-textarea></b-form-textarea>
</template>
```

> Test case:
> - Type something in textarea
> - Character seems to be trimmed off

Screen recording:
https://www.dropbox.com/s/qn416h75t7sj4z9/2018-11-11%2023-23-53.mp4?dl=0

**Comment by af-olivares10** [comment]
Try using basic HTML's 'textarea' tag using the 'form-control' class: 
`    <textarea
    class = "form-control"
    >
  </textarea>`
