### ISSUE TITLE
Accordion issue

### ISSUE THREAD

**Issue by ionesculiviucristian** [coreui/coreui-free-bootstrap-admin-template#449]
Hi. Is the accordion supposed to look like this?
https://coreui.io/docs/components/collapse/

Mine looks like this (Ubuntu, Chrome):
![untitled](https://user-images.githubusercontent.com/7398490/49087934-e0f90b00-f260-11e8-8340-193833fa4129.png)

**Comment by ubugnu** [comment]
Workaround: replace each `<div class="card">` by `<div class="card mb-0">`
![image](https://user-images.githubusercontent.com/1108370/49135702-c9189a00-f2e7-11e8-85a8-f7f96a9eab1c.png)
