### ISSUE TITLE
node_modules?

### ISSUE THREAD

**Issue by ASKemp** [coreui/coreui-free-bootstrap-admin-template#463]
The files in the download/repo reference files in the node_modules directory, but that exists outside of the src directory and is empty?

Am I meant to generate those files?

**Comment by ASKemp** [comment]
For context, I'm using the templates as a guide for a .Net Core application so need to reference the files themselves and convert as necessary rather than use direct. E.g. I see no coreui-icons.min.css file, no coreui.min.js file etc. in the download.

**Comment by xidedix** [comment]
hi @ASKemp 
afaik the `dotnet build` process restores npm dependencies on the first run

**Comment by ASKemp** [comment]
Okay, have got node.js and npm, run npm install in the project directory as directed in the readme but I get a bunch of npm ERR! errors. Lots of no such file or directory, also UNABLE_TO_GET_ISSUER_CERT_LOCALLY so not sure.

This is all outside of .net at this point.

**Comment by moreiraandre** [comment]
maybe solve your problem...
```
npm config set strict-ssl false
```
https://github.com/nodejs/node/issues/3742

**Comment by ASKemp** [comment]
Thanks. My issue was that the additional files I was looking for, coreui.js, coreui.min.js etc. are in the CoreUI master repo, not in this one, so need to get that as well for updates.
