### ISSUE TITLE
React Ladda stopped working in version 1.8.14

### ISSUE THREAD

**Issue by igordonin** [coreui/coreui-free-bootstrap-admin-template#464]
I noticed the vendors/ladda/_ladda.scss is gone. 

We have functionality that depends on that. Is there a workaround for ladda buttons, has it been deprecated, or what?

Thanks in advance.

**Comment by xidedix** [comment]
hi @igordonin 
please help us to narrow down the search
we are talking about stale version 1.8.14 
- which framework/blend?
- which revision containing `_ladda.scss` works for you?

**Comment by xidedix** [comment]
looks like `_ladda.scss` is long gone
```bash
git log --full-history -1 -- _Angular/src/scss/vendors/ladda/_ladda.scss
```
```
commit 81bca628667cf18ded2fbc2a6ec21a7b6d61db79
Merge: 09838d6e 9cbf7496
Author: Łukasz Holeczek 
Date:   Mon Oct 2 10:42:26 2017 +0200
    Merge pull request #47 from mrholek/vendors-clean-up
    Vendors clean up
```

**Comment by igordonin** [comment]
True. We got it back from version control. It was React's ladda. 

Not sure what the vendors clean up accomplished. We had something that worked and suddenly did not anymore. But whatever, it's fixed.

Thanks for your time.

**Comment by xidedix** [comment]
@igordonin
Sorry for the inconvenience, we are glad you got it fixed.
And thanks for the feedback!
