### ISSUE TITLE
Modals cause logo and aside menu to move

### ISSUE THREAD

**Issue by ASKemp** [coreui/coreui-free-bootstrap-admin-template#471]
When opening a modal the nav logo and aside menus are displaced to the right, they move back on closing the modal.

**Comment by xidedix** [comment]
hi @ASKemp 
any steps to reproduce?

**Comment by ASKemp** [comment]
Actually, possibly my implementation (.net core with partials etc.), can't reproduce in the documentation modal examples so will have to try and simplify things down.

**Comment by ASKemp** [comment]
Coming back to this, think it's because the modal removes any vertical scroll and causes right aligned content to move to the right.
If you go to the docs page for modals at  https://coreui.io/docs/components/modal/ and reduce the viewport to get the central COREUI logo brand in the top bar and then open one of the demo modals, you'll see the brand logo jump to the right then jump back left when the modal is closed.
On a larger viewport the "Contact & Support" button shifts. 

This has the same affect if an aside menu is open, causing it to jump right. 

Not sure if anything can be done since it's the function of Bootstrap modals to alter the scroll functionality I believe to scroll the modal contents.

**Comment by xidedix** [comment]
hi @ASKemp 
thanks for the follow-up - unfortunately, I still cannot reproduce this issue at https://coreui.io/docs/components/modal/  nor at localhost

**Comment by ASKemp** [comment]
Still getting it here :) 
At small and medium breakpoints, the COREUI brand logo will shift to the right when clicking to open a test modal as the vertical scrollbar is removed (Windows, IE, Chrome & FF) - actually, on the docs page at the S and MD points, the COREUI brand slips below the nav bar in IE11.

**Comment by xidedix** [comment]
@ASKemp - thanks for the catch (CoreUI brand slips below the nav bar in IE11) - the issue occurs only in the docs, it does not appear in the current version `@coreui/coreui`
