### ISSUE TITLE
Sidebar items don't work in mobile portrait view while using Turbolinks 5

### ISSUE THREAD

**Issue by pututbawono** [coreui/coreui-free-bootstrap-admin-template#476]
**What I'm using :**
1. Laravel 5.8
2. Turbolinks 5
3. Core UI 2.1.9

**The problem :**
Menu items in sidebar (menu dropdowns and menu links) won't work after the initial load of a page, but this only happens in mobile portrait view. When I change to landscape, oddly all of the sidebar items work as intended. This problem happened when I started to use Turbolinks (meaning no problem whatsoever when using "standard" page loading).

**The question :** 
Anyone can point me to the right direction on how to fix this ? I'm very new at web programming actually, and I've been searching the web for the solution.
Thanks.

**Comment by tuanlqimt** [comment]
I have the same issue with Rails 5.2.3 + Turbolinks 5.2 + CoreUI 2.1.12
Only happens in mobile
