### ISSUE TITLE
Sidebar menu items wrap issue

### ISSUE THREAD

**Issue by projectorchid** [coreui/coreui-free-bootstrap-admin-template#478]
![image-2019-04-24-20-34-41-880](https://user-images.githubusercontent.com/34150735/58081842-65569600-7bd3-11e9-8367-cfc420b56a02.png)

Is there a way not to wrap the menu item text under the icon and display the badge on first line itself?

**Comment by xidedix** [comment]
hi @projectorchid 
let's play around with styles, sth like:
```html
<a class="nav-link d-flex" href="after.html">
  <i class="nav-icon icon-calculator align-self-center"></i>After school program
  <span class="badge badge-info align-self-center">NEW</span>
</a>
```

**Comment by projectorchid** [comment]
Thanks @xidedix 
These menu items are dynamically added from database. The style fix works for the long menu links. But for shorter links like "Un Grouped" or "My First Group" the badge displays near the text, not right aligned.

**Comment by xidedix** [comment]
what about:
```html
<span class="flex-grow-1">My First Group</span>
```

to make it right for sidebar minimized add:
```css
.sidebar-minimized .sidebar .nav-link {
    display: block !important;
}
```

**Comment by dimitor115** [comment]
I've got a similar issue. If the text of the nav-link is too long, it wraps under the icon. It looks quite bad. 
![image](https://user-images.githubusercontent.com/3342963/60334067-e9eac000-999a-11e9-9013-81cd8f62cd85.png)
My solution, is to chage `nav-link` display to flex and fix `nav-icon` padding. If you have better ideas, let me know!
```
.sidebar .nav-dropdown-items .nav-item .nav-link { display: flex }
.sidebar .nav-dropdown-items .nav-item .nav-icon { padding-top:4px }
```
After that it looks much nicer !
![image](https://user-images.githubusercontent.com/3342963/60339060-f4f81d00-99a7-11e9-919c-49b49a478825.png)

**Comment by lichbx1** [comment]
> I've got a similar issue. If the text of the nav-link is too long, it wraps under the icon. It looks quite bad.
> ![image](https://user-images.githubusercontent.com/3342963/60334067-e9eac000-999a-11e9-9013-81cd8f62cd85.png)
> My solution, is to chage `nav-link` display to flex and fix `nav-icon` padding. If you have better ideas, let me know!
> 
> ```
> .sidebar .nav-dropdown-items .nav-item .nav-link { 
>      display: flex;
>     .nav-icon { 
>         padding-top:4px ;
>      }
>  }
> ```
> 
> After that, it looks much nicer!
> ![image](https://user-images.githubusercontent.com/3342963/60339060-f4f81d00-99a7-11e9-919c-49b49a478825.png)

thank you.
