### ISSUE TITLE
jQuery dependency list

### ISSUE THREAD

**Issue by jordanboston** [coreui/coreui-free-bootstrap-admin-template#479]
If this project relies on jQuery, this is a no go for use in our Vue project.  These two do not play nice together, and we specifically won't use jQuery in this project at all.

Is there a list you have of which features will be dependent on jQuery?

It would be nice if this followed the same pattern as [bootstrap-vue](https://bootstrap-vue.js.org/) in not relying on jQuery at all.

**Comment by xidedix** [comment]
Hi @jordanboston 
There is a separate CoreUI for Vue version. It has no jquery dependencies at all.
https://github.com/coreui/coreui-free-vue-admin-template

**Comment by jordanboston** [comment]
Ok, that is great!  Thanks @xidedix 

I did not realize it, I have gotten a little lost looking around in here and getting started.  👍
