### ISSUE TITLE
How to add Fade in And Fade out effect on div element in Angular 6.

### ISSUE THREAD

**Issue by hirocsingh** [coreui/coreui-free-bootstrap-admin-template#488]
## How to add Fade in And Fade out effect on div element in Angular 6.

I am aware of Fade in effect but coreui doesn't have any effects for fade out effects on div elements. I have tried multiple ways but none worked. I am also aware of Angular animation but the doesn't work as well

**Comment by mrholek** [comment]
We have dedicated project for Angular, so you asked in wrong place
