### ISSUE TITLE
document.body is null - TypeError: Cannot read property 'hasAttribute' of null

### ISSUE THREAD

**Issue by ertejaspatel** [coreui/coreui-free-bootstrap-admin-template#498]
Not sure why but document.body is null or undefined

const getjQuery = () => {
  const { jQuery } = window
  if (jQuery && !document.body.hasAttribute('data-no-jquery')) {
    return jQuery
  }
  return null
}

**Comment by johaned** [comment]
Probably you are defining the coreui js bundle when all your document is not loaded yet, you could solve this by adding an `onload` / `DOMContentLoaded` event or moving the script tag into the body tag like this https://stackoverflow.com/questions/27833117/typeerror-document-body-is-null
