### ISSUE TITLE
Accordion expand/collapse sidebar nav items feature

### ISSUE THREAD

**Issue by jameswilson** [coreui/coreui-free-bootstrap-admin-template#502]
For sites that have several top level and second level sidebar navigation elements, it would be extremely helpful to have a feature toggle (e.g., via adding a class to the sidebar nav wrapper) that collapses other expanded top-level items when another top-level link is clicked.  This is akin to the Bootstrap accordion collapse feature https://getbootstrap.com/docs/4.0/components/collapse/#accordion-example

**Comment by jameswilson** [comment]
I just noticed this was implemented in coreui version 3.0 with `data-drodpown-accordion="true"` (which incidentally 'drodpown' is spelled wrong --  not sure if intentional, or accidental).

**Comment by jameswilson** [comment]
Is there a suggested method for doing `data-drodpown-accordion="true"` with version 2.x?

**Comment by mrholek** [comment]
@jameswilson I fix it next release. This feature is only available in v3.

**Comment by jameswilson** [comment]
Ok.  Will close and open a separate bug about the spelling error.
