### ISSUE TITLE
Accordion dropdown data attribute misspelled

### ISSUE THREAD

**Issue by jameswilson** [coreui/coreui-free-bootstrap-admin-template#503]
In v3-next branch,  there is a new feature to collapse sidebar dropdowns, but it is misspelled:

```
data-drodpown-accordion="true"
```

should be :
```
data-dropdown-accordion="true"
```

This is a follow-up issue for #502

**Comment by xidedix** [comment]
@jameswilson thanks for the catch!

**Comment by mrholek** [comment]
@jameswilson will be solved in the next release.
