### ISSUE TITLE
app-sidebar.service.d.ts(6,20): error TS1005: ';' expected.

### ISSUE THREAD

**Issue by Cesaragsilva** [coreui/coreui-free-bootstrap-admin-template#506]
Guys, help me, please!

So, i'm get this error when i run "ng build".

ERROR in node_modules/@coreui/angular/lib/sidebar/app-sidebar.service.d.ts(6,20): error TS1005: ';' expected.
node_modules/@coreui/angular/lib/sidebar/app-sidebar.service.d.ts(6,55): error TS1005: '(' expected.
node_modules/@coreui/angular/lib/sidebar/app-sidebar.service.d.ts(8,18): error TS1005: ',' expected.
node_modules/@coreui/angular/lib/sidebar/app-sidebar.service.d.ts(8,35): error TS1005: ';' expected.
node_modules/@coreui/angular/lib/sidebar/app-sidebar.service.d.ts(8,41): error TS1109: Expression expected.
node_modules/@coreui/angular/lib/sidebar/app-sidebar.service.d.ts(9,1): error TS1128: Declaration or statement expected.

My package.json

{
  "name": "@coreui/coreui-free-angular-admin-template",
  "version": "3.0.0-rc.0",
  "description": "CoreUI Free Angular 2+ Admin Template",
 ...
  "private": true,
  "dependencies": {
    "@angular-devkit/build-angular": "^0.12.4",
    "@angular/animations": "^6.1.10",
    "@angular/cdk": "^6.4.7",
    "@angular/common": "^6.1.10",
    "@angular/compiler": "^6.1.10",
    "@angular/core": "^6.1.10",
    "@angular/forms": "^6.1.10",
    "@angular/http": "^6.1.10",
    "@angular/material": "^6.4.7",
    "@angular/platform-browser": "^6.1.10",
    "@angular/platform-browser-dynamic": "^6.1.10",
    "@angular/router": "^6.1.10",
    "@auth0/angular-jwt": "^1.2.0",
    "@coreui/angular": "^2.5.3",
    "@coreui/coreui": "^3.0.0-rc.0",
    "@coreui/coreui-plugin-chartjs-custom-tooltips": "^1.3.1",
    "@coreui/icons": "^0.3.0",
    "@ng-bootstrap/ng-bootstrap": "^3.3.1",
    "@ngx-pwa/local-storage": "^6.2.4",
    "bootstrap": "^4.3.1",
    "chart.js": "^2.8.0",
    "core-js": "^2.6.9",
    "flag-icon-css": "^3.3.0",
    "font-awesome": "^4.7.0",
    "moment": "^2.24.0",
    "mutationobserver-shim": "^0.3.3",
    "ng-snotify": "^4.3.1",
    "ng2-charts": "^1.6.0",
    "ngx-bootstrap": "^3.3.0",
    "ngx-perfect-scrollbar": "^6.3.1",
    "ngx-toastr": "^8.10.2",
    "rxjs": "6.5.4",
    "rxjs-compat": "6.5.4",
    "simple-line-icons": "^2.4.1",
    "ts-helpers": "^1.1.2",
    "zone.js": "^0.8.29"
  },
  "devDependencies": {
    "@angular/cli": "^6.2.9",
    "@angular/compiler-cli": "^6.1.10",
    "@angular/language-service": "^6.1.10",
    "@types/node": "^10.14.9",
    "codelyzer": "^4.5.0",
    "ts-node": "^6.2.0",
    "tslint": "^5.17.0",
    "typescript": "~2.8"
  },
  "engines": {
    "node": ">= 8.9.4",
    "npm": ">= 5.6.0"
  }
}

**Comment by xidedix** [comment]
@Cesaragsilva 
There is no such thing as `@coreui/coreui-free-angular-admin-template",
"version": "3.0.0-rc.0",` for sure.
