### ISSUE TITLE
CoreUI Pro 3 (rc) - dark-theme

### ISSUE THREAD

**Issue by DubStepMad** [coreui/coreui-free-bootstrap-admin-template#507]
- OS: Windows 10
- Node Version: 13
- CoreUI Version: 3.0.0-rc

I do have a Pro license but I can't find any documentation if I need to put this somewhere.

After changing the `src/scss/styles.scss` file to allow the dark theme, there seems to be a missing `node_module` .

Debug Log: https://pastebin.com/QUPvPsDU

Bash Output: https://pastebin.com/aHptaqfD

**Comment by xidedix** [comment]
Hi @DubStepMad 

For CoreUI Pro v3 there is no need to change `src/scss/styles.scss`.
You can switch to the dark theme by adding `c-dark-theme` class to the `c-app` element.

**Comment by DubStepMad** [comment]
@xidedix Thank you very. Spent 4 hours trying to figure this out.

Can I recommend that the README file or some sort of documentation be updated regarding this as its not stated anywhere.

**Comment by kierandevuk** [comment]
I am surprised this is not noted anywhere, as other people have had the same issue..

**Comment by jwon-klc** [comment]
+ 1

> I am surprised this is not noted anywhere, as other people have had the same issue..

+1
