### ISSUE TITLE
[BUG] Website builds without icons or functional dropdown menu

### ISSUE THREAD

**Issue by c0fe** [coreui/coreui-free-bootstrap-admin-template#508]
The issue is when building the website through npm, the end result is a website without icons or functional dropdown menus:

**Error:**
https://i.imgur.com/6FJQ9SE.png

**Working:**
https://i.imgur.com/cHHOVTn.png

The links are there but they do not function properly as they do in the demo.

**Comment by meetthosar** [comment]
Any solution?

Need urgent help!

**Comment by xidedix** [comment]
Make sure you've got installed "@popperjs/core": "^2.0.6" with CoreUI template dependencies:
`npm i @popperjs/core`

**Comment by meetthosar** [comment]
Sites are working from last 6 months, Suddenly stopped. broken CSS, no drop down working.

Do I need to update anything?

**Comment by xidedix** [comment]
What's your version of CoreUI template?

**Comment by mrholek** [comment]
@meetthosar do you import CoreUI form unpkg?

**Comment by meetthosar** [comment]
Yes I  import CoreUI form unpkg.

I am using it under one Laravel package

**Comment by mrholek** [comment]
Yesterday we released CoreUI 3.0.0, so now it's default version on unpkg. You have to add a version of CoreUI library to unpkg link, I assume that in your case you should use those links:

- CSS - https://unpkg.com/browse/@coreui/coreui@2.1.16/dist/css/coreui.min.css
- JS - https://unpkg.com/browse/@coreui/coreui@2.1.16/dist/js/coreui.min.js

**Comment by meetthosar** [comment]
Yeah!! Thank you so much!!

**Comment by c0fe** [comment]
My issue persists.

**Comment by mrholek** [comment]
@c0fe please try change https://unpkg.com/browse/@coreui/coreui/dist/js/coreui.min.js to https://unpkg.com/browse/@coreui/coreui/dist/js/coreui.bundle.min.js

or 

add https://unpkg.com/@popperjs/core@2 before https://unpkg.com/browse/@coreui/coreui/dist/js/coreui.min.js

**Comment by c0fe** [comment]
@mrholek is that in package.json?
