### ISSUE TITLE
hot reload not work

### ISSUE THREAD

**Issue by oceanpad** [coreui/coreui-free-bootstrap-admin-template#509]
Hi,
I had installed all the dependencies.
When I run `npm run server`, the browser will open a new tab, when I try to change some HTML files inside src folder, the `hot reload` doesn't work, do somebody has the same issue? or do I need to run another command?

Thanks & Best Regard

**Comment by wellangular** [comment]
run : ng serve --poll=2000 command .it is working

**Comment by xidedix** [comment]
what about `npm run watch` ?

**Comment by rdehuyss** [comment]
same here...

**Comment by mrichman** [comment]
Should this work if i edit .pug files? I'm doing `npm run serve` and if I edit say `head.pug` I don't see anything reload.

**Comment by danilopaulinodasilva** [comment]
Same problem here :/

**Comment by erwanari211** [comment]
I am running 2 terminal. 
One terminal running `npm run serve` and another terminal running `npm run watch-css`
