### ISSUE TITLE
Incorrect Unpkg Version

### ISSUE THREAD

**Issue by thoseposers** [coreui/coreui-free-bootstrap-admin-template#510]
When following the documentation for 2.x and using the demo scripts provided the 3.0 version is loading from Unpkg.

Documentation:
```
<link rel="stylesheet" href="https://unpkg.com/@coreui/coreui/dist/css/coreui.min.css">
<script src="https://unpkg.com/@coreui/coreui/dist/js/coreui.min.js"></script>
```

Urls loaded:
https://unpkg.com/@coreui/coreui@3.0.0/dist/css/coreui.min.css
https://unpkg.com/@coreui/coreui@3.0.0/dist/js/coreui.min.js

This broke a demo design until I manually swapped to these urls:
https://unpkg.com/@coreui/coreui@2.1.16/dist/css/coreui.min.css
https://unpkg.com/@coreui/coreui@2.1.16/dist/js/coreui.min.js

**Comment by Fynxh** [comment]
thank you so much, its works!!!!!
