### ISSUE TITLE
c-dark-theme toggle between pages

### ISSUE THREAD

**Issue by Afitzwater** [coreui/coreui-free-bootstrap-admin-template#517]
I currently have coreui dark theme toggle working, it correctly toggles between light and dark mode. The problem is it doesn't remember the setting between pages or reloads. 

Things i have done to debug: 
 **double checked all tags on the button** (i am using fontawesome icons instead of coreui)-
`              <ul class="c-header-nav mfs-auto">
                <li class="c-header-nav-item px-3 c-d-legacy-none">
                  <button class="c-class-toggler c-header-nav-btn" type="button" id="header-tooltip" data-target="body" data-class="c-dark-theme" data-toggle="c-tooltip" data-placement="bottom" title="Toggle Light/Dark Mode">
                    <i class="c-icon c-d-dark-none fas fa-moon "></i>
                    <i class="c-icon c-d-default-none fas fa-sun"></i>
                  </button>
                </li>
              </ul>`

**all updated scripts are called correctly**
**all css scripts are called correctly and updated**
**no JS errors on page load**

**Comment by ReArmedHalo** [comment]
Your question was from March so not sure if still relevant / needed but I've done something like this for now during development (as this isn't builtin functionality):

HTML:
```html
<ul class="c-header-nav mfs-auto">
    <li class="c-header-nav-item px-3 c-d-legacy-none">
        <button class="c-header-nav-btn" type="button" title="Toggle Light/Dark Mode" onclick="toggleColorScheme()">
            <i class="c-icon c-d-dark-none far fa-moon" aria-hidden="true"></i>
            <i class="c-icon c-d-default-none far fa-sun" aria-hidden="true"></i>
        </button>
    </li>
</ul>
```

Script at the end of body:
```javascript
<script type="text/javascript">
    function toggleColorScheme() {
        // TODO: Fire axios call to save preference so it can be loaded with PHP
        // That should prevent the "page flicker" during loading
        // This works great, but ignores user preference - We need light, dark, and system option on backend profile
        // (default should be system until user clicks color switcher, for now we are defaulting to light)
        if (document.body.classList.contains('c-dark-theme')) {
            document.body.classList.remove('c-dark-theme');
            localStorage.setItem('ColorScheme', 'light');
        } else {
            document.body.classList.add('c-dark-theme');
            localStorage.setItem('ColorScheme', 'dark');
        }
    }

    function loadColorScheme() {
        if (localStorage.getItem('ColorScheme') == 'dark') {
            document.body.classList.add('c-dark-theme');
        } else {
            localStorage.setItem('ColorScheme', 'light');
        }
    }
</script>
```
