### ISSUE TITLE
Hi. I'm new to development field. I just download and try to run CoreUI admin template, but it didn't load properly. Can't find this folder path in the files."node_modules/@coreui/chartjs/dist/css/coreui-chartjs.css. Please help.. Thank you.

### ISSUE THREAD

**Issue by tharukan** [coreui/coreui-free-bootstrap-admin-template#523]
Before opening an issue:

- [Search for duplicate or closed issues](https://github.com/coreui/coreui-free-bootstrap-admin-template/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/coreui/coreui-free-bootstrap-admin-template/blob/master/CONTRIBUTING.md)

When asking general "how to" questions:

- Please do not open an issue here

When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Reduced test cases and potential fixes using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

When suggesting a feature, include:

- As much detail as possible for what we should add and why it's important to CoreUI Admin Template
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by tjbanks** [comment]
Did you try running with NPM? I'm fairly new to this package and it may not be the best solution (please correct me if I'm wrong) but you can run it in NPM and copy any files you might need out if you're running on a different service.

```
# From linux (ubuntu for example) you may need to upgrade your npm command
# sudo apt install npm
# npm cache clean -f
# sudo npm install -g n
# sudo npm stable

# clone the repo
$ git clone https://github.com/coreui/coreui-free-bootstrap-admin-template.git my-project

# go into app's directory
$ cd my-project

# install app's dependencies
$ npm install

$ npm run serve
```
