### ISSUE TITLE
Legacy 3.0 theme

### ISSUE THREAD

**Issue by dragonattack** [coreui/coreui-free-bootstrap-admin-template#524]
How themes are supposed to work?
For example we have [regular](https://coreui.io/demo/3.1.0/) and [legacy](https://coreui.io/demo/3.1.0/legacy/) themes.

How can I apply legacy theme?

**Comment by mrholek** [comment]
Do you use CoreUI or CoreUI PRO?

**Comment by dragonattack** [comment]
CoreUI. I don't need dark theme.
But I prefer colors of CoreUI 2.0.

**Comment by mrholek** [comment]
The legacy theme is only available in CoreUI PRO

**Comment by dragonattack** [comment]
Okay. Could you please give a tip (or link) on how themes are working?
I'll make my own theme to override default colors.

**Comment by prvillanuevajr** [comment]
How do you apply legacy theme in coreui pro?
