### ISSUE TITLE
[BUG] Pretty scrollbar hides after sidebar collapsed

### ISSUE THREAD

**Issue by Kazem-ma79** [coreui/coreui-free-bootstrap-admin-template#525]
When collapse then uncollapse left sidebar, scrollbar changes to default scrollbar.

**Comment by xidedix** [comment]
Does this issue also occur here: https://coreui.io/demo/ ?

**Comment by KAJOOSH** [comment]
I have this problem too
But this problem does not exist in demo
tested: Version 3.0.0 & 3.1.1 
tested: Version v3.0.0-rc.0 (This is no problem)
