### ISSUE TITLE
bug: popper.scheduleUpdate is not a function (3.1.1)

### ISSUE THREAD

**Issue by KAJOOSH** [coreui/coreui-free-bootstrap-admin-template#526]
Hello
When using the version: 3.1.1: 
popper.scheduleUpdate is not a function
This problem did not exist in the previous version

**Comment by KAJOOSH** [comment]
what's the solution ?!
Isn't anyone responsible here?!

**Comment by robdavey555** [comment]
You can head over to https://coreui.io/pro/#c-pricing-new and get a paid version for any urgent support

**Comment by mrholek** [comment]
It's fixed in the latest release
