### ISSUE TITLE
Using vh-100 in card body expand it to more than page size creating a verticall scroll

### ISSUE THREAD

**Issue by ccamacho** [coreui/coreui-free-bootstrap-admin-template#527]
Hi,

I'm playing with the demo and I'm trying to create a body card that fills the page without creating a vertical scroll,  but I'm unable to do it using the vh-100 class.

For example in the google maps view.

![screen-1](https://user-images.githubusercontent.com/17335512/83500222-c55a6a80-a4be-11ea-968f-b76995f60844.PNG)

I will like to fill the page using the card body but without creating a vertical scroll as there is no need for it.

![screen-2](https://user-images.githubusercontent.com/17335512/83500412-06527f00-a4bf-11ea-87d9-76e0ad3f92b5.PNG)

As you can see when adding the vh-100 class, the card body expands to the end of the page creating the vertical scroll which is not needed.

The size of the vh-100 should end at the end of the page with something like the following image.

![screen-3](https://user-images.githubusercontent.com/17335512/83500496-1ff3c680-a4bf-11ea-91d1-703db49af972.PNG)

Is this a style class redefined in core-ui? Is there a way to achieve this? Or this is a bug?.

Thanks!
Carlos.

**Comment by ccamacho** [comment]
This is what I spect (I create it with paint)

![result](https://user-images.githubusercontent.com/17335512/83530649-4c720780-a4ec-11ea-8a94-a1582f3da34b.png)

**Comment by ccamacho** [comment]
@xidedix @mrholek can you give a hand with this? Thanks!

**Comment by niklasp** [comment]
go for `calc` and substract footer and header heights ( fixed and known )

**Comment by niklasp** [comment]
```
.card {
  height: calc(100vh - 50px - 80px);
}
```
