### ISSUE TITLE
Style CSS is Missing

### ISSUE THREAD

**Issue by willydavidjr** [coreui/coreui-free-bootstrap-admin-template#528]
Hi,

I downloaded your repo. Unfortunately it's not rendering properly. It's looking for the style.css under css folder. I check your repo here but there is not css folder nor style.css. Here is the screenshot of my error:

![image](https://user-images.githubusercontent.com/20619236/83773739-7fb4c200-a6b7-11ea-8b89-89675cc37c6e.png)

To reproduce the error. Download the repo, and open the src folder and open index.html in Google Chrome.

**Comment by Dreamer1007** [comment]
me too

**Comment by mrholek** [comment]
Our admin template requires node.js. First, you have to install all project dependencies, and then run the project. Please try this

# install app's dependencies
$ npm install

# serve with hot reload at localhost:3000.
$ npm run serve
