### ISSUE TITLE
IE11, Object doesn't support this action error

### ISSUE THREAD

**Issue by ing-garcia** [coreui/coreui-free-bootstrap-admin-template#530]
using coreui.bundle.min.js, both from local environment and from CDN, is causing this error on IE 11 version 11.1217.17763.0

`SCRIPT445: Object doesn't support this action
coreui.bundle.min.js (6,3135)`

How can this be fixed? Dropdowns and the sidebar toggle is not working.

**Comment by mrholek** [comment]
It will be solved in next release.

**Comment by ing-garcia** [comment]
thank you for the quick response, when is the next release expected?

**Comment by mrholek** [comment]
Next week

**Comment by ing-garcia** [comment]
problem is related to CustomEvent on ie 11

**Comment by mrholek** [comment]
Fixed in the latest version
