### ISSUE TITLE
ie-custom-properties.scss generate styles which are marker as errors by sonar scanner as invalid property

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [coreui/coreui-free-bootstrap-admin-template#535]
When reporting a bug, include:
OS: windows 10
Browser : Google Chrome
CoreUI version: 2.1.12
coreui/react version : 2.0.5

**Descriptions**
i did scanned code using sonar scanner and found that style.css created by coreui having class "ie-custom-properties" which have invalid properties.

Did checked the code inside `node_modules/@coreui/coreui/scss/ie-custom-properties.scss`
It create style for class .ie-custom-properties with invalid colour properties which are marked as invalid by sonar scanner.

Following is the output of scss which have issues/invalid css properties. Because there are not any css properties like this
```
.ie-custom-properties {
  blue: #20a8d8;
  indigo: #6610f2;
  purple: #6f42c1;
  pink: #e83e8c;
  red: #f86c6b;
....
}
```

**Comment by xidedix** [comment]
Hello @AbhaysinghBhosale, 

You're 100% right, these are not valid properties. 
They are internally used by CoreUI for IE support only.

**Comment by AbhaysinghBhosale** [comment]
@xidedix Is there any workaround for this to fix scan issues for style.css,
Because sonar scanner scan all the code in application and generated class "ie-custom-properties" reported as invalid/bug.

Is there any plan to fix/change this?
