### ISSUE TITLE
Missing CSS Source Files

### ISSUE THREAD

**Issue by imabhijithp** [coreui/coreui-free-bootstrap-admin-template#536]
Missing CSS Source files & folder in /src/

**Comment by megilangr1** [comment]
Up

**Comment by mrholek** [comment]
This admin is based on our components library [@coreui/coreui](https://github.com/coreui/coreui), so source files are available after installation in node_modules/@coreui/coreui/

**Comment by imabhijithp** [comment]
Oh okay , installing through npm. Got it , thanks anyway
