### ISSUE TITLE
[PRO] - Dark Mode - Select2 dropdown is transparent

### ISSUE THREAD

**Issue by shubhamranjan** [coreui/coreui-free-bootstrap-admin-template#539]
Hi,

I felt this medium would help my issue get highlighted as I was not getting a response through the pro support channel (Request ID - 3315). 

Version: 3.2.0
Theme: Dark Mode
Forms -> Advanced -> Select2 (Choose any select2 dropdown)

This is was it looks like:

![image](https://user-images.githubusercontent.com/12862441/87807874-64bc9c80-c876-11ea-8669-2df63b7e2c37.png)

This issue is also replicable on your live demo here: https://coreui.io/demo/3.1.0/dark/#forms/advanced-forms.html

**Comment by abunch** [comment]
@shubhamranjan did support ever address your issue?  I've been having a difficult time getting a response as well to an issue with dark mode (also the PRO version).

**Comment by shubhamranjan** [comment]
@abunch - I eventually got a reply via email and they did deploy a fix but yeah, a delayed response.
