### ISSUE TITLE
sidebar hides when c-sidebar-nav-dropdown-toggle clicked on mobile view

### ISSUE THREAD

**Issue by matthelosh** [coreui/coreui-free-bootstrap-admin-template#540]
I have an issue when I switch to mobile view on Chrome, Firefox And Opera in windows 10x64.
I am sorry if this issue has been reported. 
I do dirty solution, because i don't know how to fix the code. My temporary solution is adding class "c-sidebar-show" to "c-sidebar" element when "c-sidebar-nav-dropdown-toggle" is clicked. And I got new issue, the sidebar won't hide when i click outside the sidebar. So I add "c-sidebar-nav-link" on the top as a toggle hide.

![image](https://user-images.githubusercontent.com/10930995/88077324-5ab3da00-cba5-11ea-8d3e-d59ccc28373d.png)

### Before 
![coreui-sidebar-issue-on-mobile](https://user-images.githubusercontent.com/10930995/88075870-90f05a00-cba3-11ea-8b42-53bfd874d4a1.gif)

### After
![solution](https://user-images.githubusercontent.com/10930995/88077137-1f191000-cba5-11ea-9532-2521ae894665.gif)

**Comment by erwanari211** [comment]
Sidebar will be hidden when clicked a link if link have `c-sidebar-nav-link` and `c-sidebar-nav-dropdown-toggle` class.
If link only have  `c-sidebar-nav-dropdown-toggle` class, sidebar will not be hidden

![image](https://user-images.githubusercontent.com/17095568/93045616-c8e6bb80-f681-11ea-9732-834a3b72e549.png)

**Comment by Muhammadinaam** [comment]
@erwanari211 , thanks. I removed "c-sidebar-nav-link" class from dropdown-toggle menu item and it is working perfectly now.
