### ISSUE TITLE
CoreUI 3.4 - Asidebar close button not working

### ISSUE THREAD

**Issue by AxiakJ** [coreui/coreui-free-bootstrap-admin-template#553]
Asidebar close button is not working. This can be reproduced in the demo version: https://coreui.io/demo/3.4.0/

### **Removing responsive="true" fixes the issue.** (temp fix?)

![image](https://user-images.githubusercontent.com/56797040/101613033-955ec780-3a0b-11eb-83f2-e465a1080455.png)

**Comment by hassandraga** [comment]
Same problem (_Pro version_).

**Comment by fklee** [comment]
Same problem, problem is visible in demo page.

**Comment by hassandraga** [comment]
Same problem in the 4.0 version (_latest_), funny.
