### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by rskhiri** [coreui/coreui-free-bootstrap-admin-template#573]
error when "npm install" and node_modules  folder is deleted

1470 verbose node v14.17.1
1471 verbose npm  v7.20.3
1472 error code E404
1473 error 404 Not Found - GET https://registry.npmjs.org/path-exists/-/path-exists-4.0.1.tgz - Not found
1474 error 404
1475 error 404 'path-exists@https://registry.npmjs.org/path-exists/-/path-exists-4.0.1.tgz' is not in the npm registry.
1476 error 404 You should bug the author to publish it (or use the name yourself!)
1477 error 404 Note that you can also install from a
1478 error 404 tarball, folder, http url, or git url.
1479 verbose exit 1

windows 10 64
npm@7.20.3

**Comment by sh-miyoshi** [comment]
I found versioning up from `4.0.0` to `4.0.1` of path-exists(*) in package-lock.json.
*) not only path-exists, but also untildify, xdg-basedir, ...
but these packages do not have `4.0.1` version.

I guess that it was accidentally updated when upgraded the core-ui version to 4.0.1.

**Comment by rskhiri** [comment]
you are probably right
I replaced "4.0.1" with "4.0.0" in package-lock.json except for coreui version and had no errors with npm install
