### ISSUE TITLE
Sidebar nav-item is hiden after Chrome Desktop update Version 105.0.5195.54

### ISSUE THREAD

**Issue by hvhai** [coreui/coreui-free-bootstrap-admin-template#596]
Hi CoreUI developers,
After Chrome update to Version 105.0.5195.54 (Official Build) (64-bit), every nav-item in sidebar is gone like below
![image](https://user-images.githubusercontent.com/25703072/187808488-6be33d7b-8f12-404b-87c2-0f8f3f4441ad.png)

## Reproduce on:
OS: Windows 10
Browser:  Chrome Version 105.0.5195.54 (Official Build) (64-bit)
[Stable Channel Update for Desktop](https://chromereleases.googleblog.com/2022/08/stable-channel-update-for-desktop_30.html)
Could you consider it and provide a solution?
Regards,

**Comment by xidedix** [comment]
confirmed

**Comment by mrholek** [comment]
@hvhai please update @coreui/coreui to v4.2.2

**Comment by hvhai** [comment]
Hi @mrholek ,
I updated @coreui/coreui to v4.2.2 in my project, but the issue was still there.
After checking the commit files, I saw that the css/style.css also was changed. I updated it to my project and then it works correctly.
Thanks for fixing it and for the beautiful template ❤️ 
Regards,
