### ISSUE TITLE
Sidebar nav-dropdown not expanding

### ISSUE THREAD

**Issue by najohnson11936** [coreui/coreui-free-bootstrap-admin-template#597]
Nav dropdowns are not expanding properly within Sidebar. The nav-group-items elements are available when inspecting but are not visible anywhere on screen. This appears to be prevalent and replicable in the docs example for Sidebar -[https://coreui.io/docs/components/sidebar/](https://coreui.io/docs/components/sidebar/)

- Windows 10 Enterprise 19044.1889
- Chrome Version 104.0.5112.102 (Official Build) (64-bit)

**Comment by alexzaugarov** [comment]
@najohnson11936 I had the same problem. Fixed by adding `data-coreui="navigation"` to `.sidebar-nav` element. You can see it in markup here https://coreui.io/demos/bootstrap/4.3/light/#
![image](https://user-images.githubusercontent.com/20421997/216252687-a1172e16-fbf2-406c-8dd2-b5a6fee95b84.png)
