### ISSUE TITLE
Tab styles are disabled inside a card

### ISSUE THREAD

**Issue by dannief** [coreui/coreui-free-bootstrap-admin-template#61]
Hi. Thanks for the great theme.

I am currently trying to add a tab inside a card but I noticed that tabs don't have the styles inside a card. Is there a reason for this? Could you point me to where I can re-enable the styles. I found the styles for the .tab-content class but the tab headers no longer have styles applied.

I am using the angular 2 version

Thanks.

**Comment by vvelkovski** [comment]
I have the same style problem using Vue version.
