### ISSUE TITLE
primeNG Components CSS problem

### ISSUE THREAD

**Issue by caglarturkurka** [coreui/coreui-free-bootstrap-admin-template#63]
Hi; I use your angular2-cli-full-project.Also I want to use primeNG components (for example,dropdown),but primeNG css and your template are interfere.Please help me about this problem.How can I solve this problem.

Thanks

**Comment by mrholek** [comment]
Hi, in Angular 2 Version i recommend to use [ng2-bootstrap](https://github.com/valor-software/ng2-bootstrap).

All components like dropdown are available. ng2-bootstrap is integrated with anngular-cli version.

**Comment by caglarturkurka** [comment]
thank you for your reply.Also you can give an advice about datatable for angular 2.Namely,you can give an alternative for primeNG datatable.

**Comment by caglarturkurka** [comment]
thank you for your reply.Also you can give an advice about datatable for
angular 2.Namely,you can give an alternative for primeNG datatable.

2016-11-07 14:30 GMT+03:00 Łukasz Holeczek <notifications@github.com>:
