### ISSUE TITLE
Card with 100% height

### ISSUE THREAD

**Issue by zrilo** [coreui/coreui-free-bootstrap-admin-template#71]
Im working with the Angular 2 version. I would like to have a card that fills 100% of the router-outlet in fulllayout. Currently i can have a card buts its height is limited to the content within it, i would like to have one card stretch vertically to fill the view

Appreciate any guidance

**Comment by tymons** [comment]
Hi zrilo,

I think this is not an Issue and this type of questions should be redirected to somewhere else, please consider it.

According to your question: I'm afraid that it wouldn't be possible in full-Layout. You have to add the new one and redirect to it with router. Look at simple-layout component.
You can find useful info  here: [LINK](https://angular.io/docs/ts/latest/guide/router.html)
