### ISSUE TITLE
Datatable Suggestion

### ISSUE THREAD

**Issue by caglarturkurka** [coreui/coreui-free-bootstrap-admin-template#72]
Hi, Please tell me which plugin is good for using datatable in angular 2

**Comment by gkTim** [comment]
Hi,

have a look at this:
http://swimlane.github.io/ngx-datatable/#

**Comment by pauloeli** [comment]
@gkTim, hi

I found problems to integrate CoreUI Pro with ngx-datatable. When I put de _custom.css the application "not compile" and the following error appears:

`ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/scss/style.scss
...
 @ ./src/scss/style.scss 4:14-199
 @ multi ./node_modules/flag-icon-css/css/flag-icon.css ./node_modules/font-awesome/css/font-awesome.css ./node_modules/simple-line-icons/css/simple-line-icons.css ./src/scss/style.scss`

Do you know anything about this problem?
Any help will be appreciated

Thanks

**Comment by gkTim** [comment]
@pauloeli Hi,

sry, I don't know about the problem.
I've created my own admin template for the project using angular material, so I'm not using coreui anymore (but it's still great).

But it seems the problem is in the styles.scss

```
./src/scss/style.scss 4:14-199 @ multi
```
