### ISSUE TITLE
Not designed for application developers

### ISSUE THREAD

**Issue by mehaase** [coreui/coreui-free-bootstrap-admin-template#73]
Hi, I really like the idea of this project. I highly appreciate the blog post where you described your purpose — so few projects have a clearly defined purpose — but from an application developer's point of view, the project is not structured in a way that makes me want to include it my open source web application.

1. **The project includes dependencies.** As an applicationd developer, I would prefer that the dependencies (e.g. Bootstrap) did not come inside this project. Instead, I would like to obtain Bootstrap separately so that I can upgrade it whenever I need to. This is especially important for Bootstrap 4, which is still in the alpha stage. I don't want to wait until Core UI makes a new release so that I can get my Bootstrap updates/bug fixes.
2. **Customizing the style requires me to modify your source code.** The project expects that I will build the `style.scss` file that comes with it. If I want to customize the theme, then I am supposed to modify the `_custom.scss` file included in the theme. This complicates my dependency management, because later if I download a new version of CoreUI and unzip it, it will overwrite my `_custom.scss`. So I have to remember to rename my custom file, unzip the new CoreUI, then put my custom file back in place.
3. **The project is not an importable component.** Related to the previous point: I don't want to build your SCSS file. I want to import your SCSS file into mine, because this theme is a component of my application, not the other way around.
4. **The modularization is good, but not complete.** I really like the ability to import specific things I want to use, e.g. `@import "core/navigation/sidebar";`. Instead of using the included `style.scss`, I could make my own stylesheet that only imports the components that I actually want to use. However, it doesn't quite work in practice because I also need to remember to import other files in the correct order, such as `custom-variables`, `core/temp`, etc. I can copy those imports from `style.scss` into my own file, but if those imports change in a future release of Core UI (e.g. some day you remove `core/_temp.scss`), then my application will break when I upgrade Core UI. Core UI should have a `core/_init.scss` that just contains the minimum amount of set up necessary to use Core UI so that I can `@import core/init` and then import the individual components that I want to use.
5. **It makes assumptions about what tools I want to use.** I personally don't use bower, or gulp, or any of the tools mentioned in your docs, and I don't see the need to force the usage of such tools just to install a Bootstrap theme. Installing the theme should be as easy as copying a directory of SCSS source code, then importing the modules that I want into my own SCSS file. It's nice if bower/gulp/whatever are additional options, but not everybody uses the same tools as you.
6. **It's not really as "lightweight as possible".** I love the the switch widgets that you made, but CoreUI contains 19 different types of switch! It may be "light" in the sense of "not many lines of code", but it's not light in terms of cognitive load. Any time I want to use a switch, I need to check which of the 19 styles I want to use. If there were 19 styles of navbar, 19 styles of sidebar, 19 styles of cards, 19 styles of everything... I would drown in the possibilities. The entire reason I seek out a Bootstrap theme is that I want somebody with more UX talent and experience than myself to make those decisions for me.

Please don't take this as harsh criticism, but as constructive feedback. I really admire the work you're doing here. A lot of other themes have these same issues, but yours is the only theme I found that is both MIT licensed and looks professional. It's a really great project overall and would be perfect if it was structured a bit differently. I think there is probably a divide between how application developers think theme development works and how theme devleopers think application development works. I hope this communication helps to cross that divide.

Cheers,
Mark

**Comment by Faerylnahr** [comment]
@mehaase I definitely agree with you! I would love if those points would be taken into account. From my point of view this would mean a huge step forward for this project! @mrholek have you already thought about these points? :)

**Comment by mehaase** [comment]
Hi @Faerylnahr, I ended up taking another [open source Bootstrap theme](https://github.com/modularcode/modular-admin-html) and remixed it into [an Angular2Dart UI framework](https://gitlab.com/hyperion-gray/ng2_modular_admin). It's still a work in progress...
