### ISSUE TITLE
Is it possible to switch the horizontal nav bar instead of the sidebar

### ISSUE THREAD

**Issue by reach2deep** [coreui/coreui-free-bootstrap-admin-template#77]
Hi,

Is it possible to change the navbar(main menu) as a top horizontal navigation menu bar ?

Thanks

**Comment by mrholek** [comment]
Hi, I'm going to add some new layout options ASAP. So horizontal navigation should be available soon.

**Comment by reach2deep** [comment]
@mrholek  thanks, trust you will add the horizontal navigation, with that hope am using your theme :)

**Comment by maelgrove** [comment]
Any updates on this @mrholek? Even though a horizontal 'navigation' exists, it's not really responsive as it just disappears on smaller screens with no way to access it. This holds true for both CoreUI and all GenesisUI templates.

**Comment by narramadan** [comment]
+1 ... I need this..

**Comment by wilsmex** [comment]
!+. As is, it's impossible to navigate to main menu pages on mobile...  I need a dropdown toggle for main menu nav on mobile

**Comment by ali-makhmali** [comment]
+1, hello guys, has this been implemented yet?

**Comment by Crunky** [comment]
+1 any updates?

**Comment by mrholek** [comment]
It will be added later this year
